INSERT INTO silver.match
SELECT
    g.match_id,
    ifNull(toDate(parseDateTimeBestEffortOrNull(g.match_time_utc_date)), ifNull(toDate(parseDateTimeBestEffortOrNull(g.match_time_utc)), toDate('1970-01-01'))) AS match_date,
    parseDateTimeBestEffortOrNull(g.match_time_utc) AS match_time_utc,
    g.match_started,
    g.match_finished,
    g.match_round,
    g.coverage_level,
    g.league_id,
    g.league_name,
    g.league_round_name,
    g.parent_league_id,
    g.parent_league_name,
    g.parent_league_season,
    g.parent_league_tournament_id,
    g.country_code,
    v.tournament_id,
    v.tournament_name,
    v.tournament_round,
    v.tournament_link,
    g.home_team_id,
    g.home_team_name,
    g.away_team_id,
    g.away_team_name,
    g.home_score,
    g.away_score,
    g.full_score,
    ifNull(t.game_started, 0) AS game_started,
    ifNull(t.game_finished, 0) AS game_finished,
    ifNull(t.game_cancelled, 0) AS game_cancelled,
    parseDateTimeBestEffortOrNull(t.first_half_started) AS first_half_started,
    parseDateTimeBestEffortOrNull(t.first_half_ended) AS first_half_ended,
    parseDateTimeBestEffortOrNull(t.second_half_started) AS second_half_started,
    parseDateTimeBestEffortOrNull(t.second_half_ended) AS second_half_ended,
    parseDateTimeBestEffortOrNull(t.first_extra_half_started) AS first_extra_half_started,
    parseDateTimeBestEffortOrNull(t.second_extra_half_started) AS second_extra_half_started,
    parseDateTimeBestEffortOrNull(t.game_ended) AS game_ended,
    v.stadium_name,
    v.stadium_city,
    v.stadium_country,
    v.stadium_latitude,
    v.stadium_longitude,
    v.stadium_capacity,
    v.stadium_surface,
    v.attendance,
    v.match_date_verified,
    v.referee_name,
    v.referee_country,
    now() AS _loaded_at
FROM bronze.general AS g FINAL
LEFT JOIN bronze.timeline AS t FINAL ON g.match_id = t.match_id
LEFT JOIN bronze.venue AS v FINAL ON g.match_id = v.match_id;
