-- Signal tables for gold layer

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_high_press_victim (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    triggered_pass_accuracy_pct Nullable(Float32),
    pass_accuracy_home_pct Nullable(Float32),
    pass_accuracy_away_pct Nullable(Float32),
    pass_accuracy_delta_pct Float32,
    pass_attempts_home Int32,
    pass_attempts_away Int32,
    own_half_pass_share_home_pct Nullable(Float32),
    own_half_pass_share_away_pct Nullable(Float32),
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_possession_without_purpose (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_acc_pct Nullable(Float32),
    opponent_pass_acc_pct Nullable(Float32),
    triggered_team_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_team_touches_opp_box Int32,
    opponent_touches_opp_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    xg_delta Float32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_shot_blocks Int32,
    opponent_shot_blocks Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_siege_mode (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_acc_pct Nullable(Float32),
    opponent_pass_acc_pct Nullable(Float32),
    triggered_team_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_team_touches_opp_box Int32,
    opponent_touches_opp_box Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_shots Int32,
    opponent_shots Int32,
    triggered_team_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_efficient_directness (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    triggered_team_xg_on_target Float32,
    opponent_xg_on_target Float32,
    xg_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_acc_pct Nullable(Float32),
    opponent_pass_acc_pct Nullable(Float32),
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_touches_opp_box Int32,
    opponent_touches_opp_box Int32,
    triggered_team_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_low_block_frustration (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_acc_pct Nullable(Float32),
    opponent_cross_acc_pct Nullable(Float32),
    triggered_team_touches_opp_box Int32,
    opponent_touches_opp_box Int32,
    triggered_team_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_team_dribbles_succeeded Int32,
    opponent_dribbles_succeeded Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_acc_pct Nullable(Float32),
    opponent_pass_acc_pct Nullable(Float32),
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_set_play Float32,
    opponent_xg_set_play Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    xg_delta Float32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_shot_blocks Int32,
    opponent_shot_blocks Int32,
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_attempts Int32,
    opponent_aerial_attempts Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_second_half_possession_collapse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    possession_drop_pp Float32,
    triggered_team_poss_fh Float32,
    triggered_team_poss_sh Float32,
    opponent_poss_fh Float32,
    opponent_poss_sh Float32,
    possession_swing_delta Float32,
    triggered_team_pass_att_fh Int32,
    triggered_team_pass_att_sh Int32,
    opponent_pass_att_fh Int32,
    opponent_pass_att_sh Int32,
    triggered_team_pass_acc_fh Nullable(Float32),
    triggered_team_pass_acc_sh Nullable(Float32),
    opponent_pass_acc_fh Nullable(Float32),
    opponent_pass_acc_sh Nullable(Float32),
    triggered_team_pass_acc_delta Nullable(Float32),
    opponent_pass_acc_delta Nullable(Float32),
    triggered_team_opp_half_passes_fh Int32,
    triggered_team_opp_half_passes_sh Int32,
    opponent_opp_half_passes_fh Int32,
    opponent_opp_half_passes_sh Int32,
    triggered_team_xg_fh Float32,
    triggered_team_xg_sh Float32,
    opponent_xg_fh Float32,
    opponent_xg_sh Float32,
    xg_swing_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_death_by_passes (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    both_sides_triggered UInt8,
    triggered_team_opp_box_touches Int32,
    opponent_opp_box_touches Int32,
    opp_box_touches_delta Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_box_touch_per_pass_pct Nullable(Float32),
    opponent_box_touch_per_pass_pct Nullable(Float32),
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_per_box_touch Nullable(Float32),
    opponent_xg_per_box_touch Nullable(Float32),
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_long_ball_desperation (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    score_margin_home_perspective Int32,
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    long_ball_attempts_delta Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Nullable(Float32),
    opponent_long_ball_accuracy_pct Nullable(Float32),
    triggered_team_long_ball_share_pct Nullable(Float32),
    opponent_long_ball_share_pct Nullable(Float32),
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_success_pct Nullable(Float32),
    opponent_aerial_success_pct Nullable(Float32),
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_clearances_conceded Int32,
    opponent_clearances_conceded Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_keeper_involved (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    triggered_gk_player_id Nullable(Int32),
    triggered_gk_player_name Nullable(String),
    sig_team_possession_passing_keeper_involved Int32,
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    possession_delta Float32,
    pass_attempt_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1), ifNull(triggered_gk_player_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_failed_penetration (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_team_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_touches_opp_box Int32,
    triggered_shots_inside_box Int32,
    opponent_touches_opp_box Int32,
    opponent_shots_inside_box Int32,
    triggered_touches_per_box_shot Nullable(Float32),
    opponent_touches_per_box_shot Nullable(Float32),
    triggered_total_shots Int32,
    opponent_total_shots Int32,
    triggered_xg Float32,
    opponent_xg Float32,
    triggered_big_chances Int32,
    triggered_big_chances_missed Int32,
    opponent_big_chances Int32,
    opponent_big_chances_missed Int32,
    triggered_accurate_crosses Int32,
    triggered_cross_attempts Int32,
    triggered_cross_accuracy_pct Float32,
    opponent_accurate_crosses Int32,
    opponent_cross_attempts Int32,
    opponent_cross_accuracy_pct Float32,
    triggered_dribbles_succeeded Int32,
    triggered_dribble_attempts Int32,
    opponent_dribbles_succeeded Int32,
    opponent_dribble_attempts Int32,
    triggered_opp_half_passes Int32,
    opponent_opp_half_passes Int32,
    triggered_corners Int32,
    opponent_corners Int32,
    box_touch_delta Int32,
    xg_delta Float32,
    corners_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_team_side, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);
