-- Signal tables for gold layer

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_high_press_victim (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    triggered_team_pass_accuracy_pct Nullable(Float32),
    home_pass_accuracy_pct Nullable(Float32),
    away_pass_accuracy_pct Nullable(Float32),
    pass_accuracy_delta_pct Float32,
    pass_attempts_home Int32,
    pass_attempts_away Int32,
    own_half_pass_share_home_pct Nullable(Float32),
    own_half_pass_share_away_pct Nullable(Float32),
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_possession_without_purpose (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    xg_delta Float32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_shot_blocks Int32,
    opponent_shot_blocks Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_siege_mode (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_shots Int32,
    opponent_shots Int32,
    triggered_team_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_efficient_directness (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    triggered_team_xg_on_target Float32,
    opponent_xg_on_target Float32,
    xg_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_low_block_frustration (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Nullable(Float32),
    opponent_cross_accuracy_pct Nullable(Float32),
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_dribbles_succeeded Int32,
    opponent_dribbles_succeeded Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_set_play Float32,
    opponent_xg_set_play Float32,
    triggered_team_xg_open_play Float32,
    opponent_xg_open_play Float32,
    xg_delta Float32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_shot_blocks Int32,
    opponent_shot_blocks Int32,
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_attempts Int32,
    opponent_aerial_attempts Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_second_half_possession_collapse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    possession_drop_pp Float32,
    triggered_team_possession_first_half_pct Float32,
    triggered_team_possession_second_half_pct Float32,
    opponent_possession_first_half_pct Float32,
    opponent_possession_second_half_pct Float32,
    possession_swing_delta Float32,
    triggered_team_pass_attempts_first_half Int32,
    triggered_team_pass_attempts_second_half Int32,
    opponent_pass_attempts_first_half Int32,
    opponent_pass_attempts_second_half Int32,
    triggered_team_pass_accuracy_first_half_pct Nullable(Float32),
    triggered_team_pass_accuracy_second_half_pct Nullable(Float32),
    opponent_pass_accuracy_first_half_pct Nullable(Float32),
    opponent_pass_accuracy_second_half_pct Nullable(Float32),
    triggered_team_pass_accuracy_delta_pct Nullable(Float32),
    opponent_pass_accuracy_delta_pct Nullable(Float32),
    triggered_team_opposition_half_passes_first_half Int32,
    triggered_team_opposition_half_passes_second_half Int32,
    opponent_opposition_half_passes_first_half Int32,
    opponent_opposition_half_passes_second_half Int32,
    triggered_team_xg_first_half Float32,
    triggered_team_xg_second_half Float32,
    opponent_xg_first_half Float32,
    opponent_xg_second_half Float32,
    xg_swing_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_death_by_passes (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    both_sides_triggered UInt8,
    triggered_team_opposition_box_touches Int32,
    opponent_opposition_box_touches Int32,
    opposition_box_touches_delta Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_box_touch_per_pass_pct Nullable(Float32),
    opponent_box_touch_per_pass_pct Nullable(Float32),
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_xg_per_box_touch Nullable(Float32),
    opponent_xg_per_box_touch Nullable(Float32),
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_long_ball_desperation (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    score_margin_home_perspective Int32,
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    long_ball_attempts_delta Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Nullable(Float32),
    opponent_long_ball_accuracy_pct Nullable(Float32),
    triggered_team_long_ball_share_pct Nullable(Float32),
    opponent_long_ball_share_pct Nullable(Float32),
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_success_pct Nullable(Float32),
    opponent_aerial_success_pct Nullable(Float32),
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_clearances_conceded Int32,
    opponent_clearances_conceded Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_keeper_involved (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    triggered_goalkeeper_player_id Nullable(Int32),
    triggered_goalkeeper_player_name Nullable(String),
    triggered_team_goalkeeper_touches Int32,
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    possession_delta Float32,
    pass_attempt_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, ifNull(triggered_team_id, -1), ifNull(triggered_goalkeeper_player_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_failed_penetration (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_touches_opposition_box Int32,
    triggered_team_shots_inside_box Int32,
    opponent_touches_opposition_box Int32,
    opponent_shots_inside_box Int32,
    triggered_team_touches_per_box_shot Nullable(Float32),
    opponent_touches_per_box_shot Nullable(Float32),
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    triggered_team_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances Int32,
    opponent_big_chances_missed Int32,
    triggered_team_accurate_crosses Int32,
    triggered_team_cross_attempts Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_accurate_crosses Int32,
    opponent_cross_attempts Int32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_dribbles_succeeded Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribbles_succeeded Int32,
    opponent_dribble_attempts Int32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    box_touch_delta Int32,
    xg_delta Float32,
    corners_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, ifNull(triggered_team_id, -1))
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_high_tempo_passing (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    home_possession_first_half_pct Float32,
    home_possession_second_half_pct Float32,
    away_possession_first_half_pct Float32,
    away_possession_second_half_pct Float32,
    home_passes_first_half Int32,
    home_passes_second_half Int32,
    away_passes_first_half Int32,
    away_passes_second_half Int32,
    home_passes_per_minute_first_half Float32,
    home_passes_per_minute_second_half Float32,
    away_passes_per_minute_first_half Float32,
    away_passes_per_minute_second_half Float32,
    home_peak_passes_per_minute Float32,
    away_peak_passes_per_minute Float32,
    home_accurate_passes_total Int32,
    away_accurate_passes_total Int32,
    home_pass_attempts_total Int32,
    away_pass_attempts_total Int32,
    home_pass_accuracy_pct Nullable(Float32),
    away_pass_accuracy_pct Nullable(Float32),
    home_minus_away_pass_accuracy_delta_pct Nullable(Float32),
    home_opposition_half_passes Int32,
    away_opposition_half_passes Int32,
    home_own_half_passes Int32,
    away_own_half_passes Int32,
    home_opposition_half_pass_pct Nullable(Float32),
    away_opposition_half_pass_pct Nullable(Float32),
    triggered_side LowCardinality(String),
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_sterile_dominance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    big_chance_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    shot_volume_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_final_third_efficiency (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_final_third_entries Int32,
    opponent_final_third_entries Int32,
    final_third_entries_delta Int32,
    triggered_team_goals_per_final_third_entry Float32,
    opponent_goals_per_final_third_entry Float32,
    goals_per_entry_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_aerial_reliance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_attempts Int32,
    opponent_aerial_attempts Int32,
    triggered_team_aerial_success_pct Float32,
    opponent_aerial_success_pct Float32,
    aerial_success_delta Float32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_long_ball_share_pct Float32,
    opponent_long_ball_share_pct Float32,
    long_ball_share_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_possession_passing_press_resistance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    triggered_team_press_actions Int32,
    opponent_press_actions Int32,
    opponent_press_actions_per_100_triggered_passes Float32,
    press_actions_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_safe_outlet (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_pass_attempts Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_long_ball_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_long_balls_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_switch_expert (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_successful_switches_proxy Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_successful_switches_proxy Int32,
    opponent_successful_switches_proxy Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_switches_proxy_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_cross_heavy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_crosses_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_unsuccessful_crosser (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_crosses_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_creative_hub (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_high_value_provider (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_expected_assists Float32,
    triggered_player_assists Int32,
    triggered_player_chances_created Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_high_turnover_risk (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_possession_losses Int32,
    triggered_player_failed_passes Int32,
    triggered_player_failed_dribbles Int32,
    triggered_player_duels_lost Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_successful_dribbles Int32,
    triggered_player_dribble_attempts Int32,
    triggered_player_dribble_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_dribbles_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_dribble_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_successful_dribbles Int32,
    triggered_player_dribble_attempts Int32,
    triggered_player_failed_dribbles Int32,
    triggered_player_dribble_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_dribbles_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_isolated_target (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_position_id Nullable(Int32),
    triggered_player_usual_playing_position_id Nullable(Int32),
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_touches_per90 Float32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_midfield_general (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_middle_third_touches_proxy Int32,
    triggered_player_total_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_overloaded_possession (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_total_touches Int32,
    triggered_player_touches_per90 Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_back_pass_heavy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_backward_sideways_passes_proxy Int32,
    triggered_player_total_passes Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_backward_sideways_pass_share_pct Float32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_recycling_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_non_final_third_passes_proxy Int32,
    triggered_player_non_final_third_pass_share_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_defensive_actions Int32,
    triggered_player_recoveries Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_vertical_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_forward_successful_passes_proxy Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_forward_successful_pass_share_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_player_possession_passing_box_penetrator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_touches_opposition_box Int32,
    triggered_player_total_touches Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);
