-- Signal tables for entity=player, family=discipline, subfamily=cards

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_walking_tightrope (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_card_minute Int32,
    triggered_player_first_yellow_card_minute Int32,
    triggered_player_yellow_cards_total Int32,
    triggered_player_red_cards_total Int32,
    triggered_player_total_cards Int32,
    score_margin_at_first_yellow Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_duels_won Int32,
    triggered_player_duels_lost Int32,
    triggered_player_tackles_won Int32,
    triggered_player_interceptions Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_iron_man_discipline (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    trigger_threshold_minutes_played Int32,
    trigger_threshold_fouls_committed Int32,
    trigger_threshold_tackles_won Int32,
    triggered_player_minutes_played Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_tackles_won Int32,
    triggered_player_tackle_attempts Int32,
    triggered_player_total_cards Int32,
    triggered_player_yellow_cards Int32,
    triggered_player_red_cards Int32,
    triggered_player_was_fouled Int32,
    tackles_won_above_threshold Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_foul_magnet (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_was_fouled Int32,
    triggered_player_was_fouled Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_total_cards Int32,
    triggered_player_yellow_cards Int32,
    triggered_player_red_cards Int32,
    triggered_player_minutes_played Int32,
    was_fouled_count_above_threshold Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_heavy_hitter (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_tackle_success_pct Float32,
    trigger_threshold_min_fouls_committed Int32,
    triggered_player_tackles_won Int32,
    triggered_player_tackle_attempts Int32,
    triggered_player_tackle_success_pct Float32,
    triggered_player_fouls_committed Int32,
    triggered_player_total_cards Int32,
    triggered_player_yellow_cards Int32,
    triggered_player_red_cards Int32,
    triggered_player_minutes_played Int32,
    tackle_success_below_threshold_pct Float32,
    foul_count_above_threshold Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_dirty_half_dozen (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_fouls_committed Int32,
    trigger_threshold_max_tackles_won Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_tackles_won Int32,
    triggered_player_tackle_attempts Int32,
    triggered_player_tackle_success_pct Float32,
    triggered_player_total_cards Int32,
    triggered_player_yellow_cards Int32,
    triggered_player_red_cards Int32,
    triggered_player_minutes_played Int32,
    foul_count_above_threshold Int32,
    tackle_attempts_without_win Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_penalty_conceder (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_penalties_conceded Int32,
    triggered_player_penalties_conceded Int32,
    triggered_player_first_penalty_conceded_minute Int32,
    triggered_player_penalties_conceded_scored Int32,
    triggered_player_penalties_conceded_missed Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_total_cards Int32,
    triggered_player_yellow_cards Int32,
    triggered_player_red_cards Int32,
    triggered_player_minutes_played Int32,
    score_margin_at_first_penalty_concession Int32,
    triggered_team_penalties_awarded Int32,
    opponent_penalties_awarded Int32,
    total_match_penalties_awarded Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_early_bath (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_red_card_minute Int32,
    triggered_player_red_card_minute Int32,
    triggered_team_score_at_red Int32,
    opponent_score_at_red Int32,
    triggered_player_red_card_count_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_late_red_drama (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_red_card_minute Int32,
    triggered_player_red_card_minute Int32,
    triggered_team_score_at_red Int32,
    opponent_score_at_red Int32,
    triggered_player_red_card_count_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_captain_reprimand (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_dissent_yellow_cards Int32,
    triggered_player_is_captain UInt8,
    triggered_player_dissent_yellow_card_minute Int32,
    triggered_team_score_at_dissent_card Int32,
    opponent_score_at_dissent_card Int32,
    score_margin_at_dissent_card Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_duels_won Int32,
    triggered_player_duels_lost Int32,
    triggered_player_tackles_won Int32,
    triggered_player_interceptions Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_double_yellow_dismissal (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_yellow_cards_for_dismissal Int32,
    triggered_player_first_yellow_card_minute Int32,
    triggered_player_second_yellow_dismissal_minute Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_total_cards_match Int32,
    triggered_team_score_at_dismissal Int32,
    opponent_score_at_dismissal Int32,
    score_margin_at_dismissal Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_duels_won Int32,
    triggered_player_duels_lost Int32,
    triggered_player_tackles_won Int32,
    triggered_player_interceptions Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_sub_card_speedrun (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_minutes_from_substitution Int32,
    triggered_player_substitution_time Int32,
    triggered_player_card_minute Int32,
    minutes_from_substitution_to_card Int32,
    triggered_player_card_event_type LowCardinality(String),
    triggered_player_score_at_card Int32,
    opponent_score_at_card Int32,
    score_margin_at_card Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_instant_impact_red (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_minutes_from_substitution Int32,
    triggered_player_substitution_time Int32,
    triggered_player_dismissal_minute Int32,
    minutes_from_substitution_to_dismissal Int32,
    triggered_player_dismissal_event_type LowCardinality(String),
    triggered_team_score_at_dismissal Int32,
    opponent_score_at_dismissal Int32,
    score_margin_at_dismissal Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_bench_discipline (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_personnel_role LowCardinality(String),
    triggered_personnel_scope LowCardinality(String),
    triggered_personnel_substitution_time Int32,
    trigger_threshold_non_playing_substitution_time Int32,
    triggered_player_card_minute Int32,
    triggered_player_card_event_type LowCardinality(String),
    triggered_team_score_at_card Int32,
    opponent_score_at_card Int32,
    score_margin_at_card Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_minutes_played Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_keeper_reckless (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_total_cards Int32,
    triggered_player_first_card_minute Int32,
    triggered_player_first_card_type LowCardinality(String),
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_minutes_played Int32,
    triggered_team_score_at_first_card Int32,
    opponent_score_at_first_card Int32,
    score_margin_at_first_card Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    triggered_team_keeper_saves Int32,
    opponent_keeper_saves Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_discipline_cards_unnecessary_card (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_score_margin_at_card Int32,
    triggered_player_first_unnecessary_card_minute Int32,
    triggered_player_first_unnecessary_card_type LowCardinality(String),
    triggered_player_unnecessary_cards_count Int32,
    triggered_player_yellow_cards_match Int32,
    triggered_player_red_cards_match Int32,
    triggered_player_total_cards_match Int32,
    triggered_player_fouls_committed Int32,
    triggered_player_was_fouled Int32,
    triggered_player_minutes_played Int32,
    triggered_team_score_at_first_unnecessary_card Int32,
    opponent_score_at_first_unnecessary_card Int32,
    score_margin_at_first_unnecessary_card Int32,
    max_score_margin_during_unnecessary_cards Int32,
    triggered_team_total_fouls Int32,
    opponent_total_fouls Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);
