-- Signal tables for entity=match, family=discipline, subfamily=cards

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_battle_of_attrition (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_combined_fouls Int32,
    match_total_fouls_committed Int32,
    match_total_fouls_above_threshold Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    match_total_cards Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_blood_and_thunder (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_combined_duels_won Int32,
    trigger_threshold_min_combined_fouls Int32,
    match_total_duels_won Int32,
    match_total_duels_won_above_threshold Int32,
    match_total_fouls_committed Int32,
    match_total_fouls_above_threshold Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    duels_won_delta Int32,
    triggered_team_duels_won_share_pct Float32,
    opponent_duels_won_share_pct Float32,
    duels_won_share_delta_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_clean_fair_play (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_combined_fouls Int32,
    trigger_threshold_max_match_total_cards Int32,
    match_total_fouls_committed Int32,
    match_total_fouls_below_threshold Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_card_frenzy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_combined_cards Int32,
    match_total_cards Int32,
    match_total_cards_above_threshold Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_share_pct Float32,
    opponent_cards_share_pct Float32,
    cards_share_delta_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_boiling_over (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_late_window_cards Int32,
    trigger_threshold_window_start_minute Int32,
    trigger_threshold_window_end_minute Nullable(Int32),
    match_late_window_cards Int32,
    match_late_window_cards_above_threshold Int32,
    home_late_window_cards Int32,
    away_late_window_cards Int32,
    triggered_team_late_window_cards Int32,
    opponent_late_window_cards Int32,
    late_window_cards_delta Int32,
    triggered_team_late_window_cards_share_pct Float32,
    opponent_late_window_cards_share_pct Float32,
    late_window_cards_share_delta_pct Float32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_stop_start_hell (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_match_minutes Int32,
    trigger_threshold_max_seconds_per_whistle Float32,
    trigger_threshold_min_combined_whistle_events Int32,
    match_total_whistle_events Int32,
    match_total_whistle_events_above_threshold Int32,
    match_seconds_per_whistle Nullable(Float32),
    match_total_fouls_committed Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    match_total_offsides Int32,
    triggered_team_whistle_events Int32,
    opponent_whistle_events Int32,
    whistle_events_delta Int32,
    triggered_team_whistle_share_pct Float32,
    opponent_whistle_share_pct Float32,
    whistle_share_delta_pct Float32,
    triggered_team_seconds_per_whistle Nullable(Float32),
    opponent_seconds_per_whistle Nullable(Float32),
    seconds_per_whistle_delta Nullable(Float32),
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_offsides Int32,
    opponent_offsides Int32,
    offsides_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_chaos_90_plus (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_added_time_red_cards Int32,
    trigger_threshold_window_base_minute Int32,
    match_added_time_red_cards Int32,
    match_added_time_red_cards_above_threshold Int32,
    home_added_time_red_cards Int32,
    away_added_time_red_cards Int32,
    triggered_team_added_time_red_cards Int32,
    opponent_added_time_red_cards Int32,
    added_time_red_cards_delta Int32,
    triggered_team_added_time_red_cards_share_pct Float32,
    opponent_added_time_red_cards_share_pct Float32,
    added_time_red_cards_share_delta_pct Float32,
    triggered_team_first_added_time_red_minute Nullable(Int32),
    opponent_first_added_time_red_minute Nullable(Int32),
    triggered_team_first_added_time_red_added_time Nullable(Int32),
    opponent_first_added_time_red_added_time Nullable(Int32),
    triggered_team_first_added_time_red_effective_minute Nullable(Int32),
    opponent_first_added_time_red_effective_minute Nullable(Int32),
    match_total_red_cards Int32,
    match_total_yellow_cards Int32,
    match_total_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_double_red_drama (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_red_cards_per_team Int32,
    home_red_cards Int32,
    away_red_cards Int32,
    match_total_red_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    match_total_cards Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_heated_derby_stats (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_combined_cards Int32,
    trigger_threshold_min_combined_fouls Int32,
    match_total_cards Int32,
    match_total_cards_above_threshold Int32,
    match_total_fouls_committed Int32,
    match_total_fouls_above_threshold Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_share_pct Float32,
    opponent_cards_share_pct Float32,
    cards_share_delta_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_unpunished_aggression (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_match_total_xg Float32,
    trigger_threshold_min_combined_fouls Int32,
    match_total_xg Float32,
    match_total_xg_above_threshold Float32,
    match_total_fouls_committed Int32,
    match_total_fouls_above_threshold Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    match_total_cards_per_foul_pct Nullable(Float32),
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_referee_strictness (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_first_yellow_card_minute_inclusive Int32,
    match_first_yellow_card_minute Int32,
    match_first_yellow_card_team_side LowCardinality(String),
    match_first_yellow_card_team_id Nullable(Int32),
    match_first_yellow_card_team_name Nullable(String),
    match_first_yellow_card_player_id Nullable(Int32),
    match_first_yellow_card_player_name Nullable(String),
    triggered_team_early_yellow_cards Int32,
    opponent_early_yellow_cards Int32,
    early_yellow_cards_delta Int32,
    match_total_early_yellow_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_referee_showdown (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_carded_captains Int32,
    match_carded_captains_count Int32,
    home_captain_player_id Nullable(Int32),
    home_captain_player_name Nullable(String),
    away_captain_player_id Nullable(Int32),
    away_captain_player_name Nullable(String),
    home_captain_total_cards Int32,
    away_captain_total_cards Int32,
    home_captain_yellow_cards Int32,
    away_captain_yellow_cards Int32,
    home_captain_red_cards Int32,
    away_captain_red_cards Int32,
    home_captain_first_card_minute Nullable(Int32),
    away_captain_first_card_minute Nullable(Int32),
    home_captain_last_card_minute Nullable(Int32),
    away_captain_last_card_minute Nullable(Int32),
    triggered_captain_player_id Nullable(Int32),
    triggered_captain_player_name Nullable(String),
    opponent_captain_player_id Nullable(Int32),
    opponent_captain_player_name Nullable(String),
    triggered_captain_total_cards Int32,
    opponent_captain_total_cards Int32,
    captain_total_cards_delta Int32,
    triggered_captain_yellow_cards Int32,
    opponent_captain_yellow_cards Int32,
    captain_yellow_cards_delta Int32,
    triggered_captain_red_cards Int32,
    opponent_captain_red_cards Int32,
    captain_red_cards_delta Int32,
    triggered_captain_first_card_minute Nullable(Int32),
    opponent_captain_first_card_minute Nullable(Int32),
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_one_sided_discipline (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_triggered_team_total_cards Int32,
    trigger_threshold_max_opponent_total_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_above_threshold Int32,
    triggered_team_cards_share_pct Float32,
    opponent_cards_share_pct Float32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_physical_showdown (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_starting_defenders Int32,
    trigger_threshold_min_cards_per_starting_defender Int32,
    triggered_team_starting_defenders Int32,
    opponent_starting_defenders Int32,
    starting_defenders_delta Int32,
    triggered_team_starting_defenders_carded Int32,
    opponent_starting_defenders_carded Int32,
    starting_defenders_carded_delta Int32,
    triggered_team_starting_defenders_carded_share_pct Float32,
    opponent_starting_defenders_carded_share_pct Nullable(Float32),
    triggered_team_cards_on_starting_defenders Int32,
    opponent_cards_on_starting_defenders Int32,
    cards_on_starting_defenders_delta Int32,
    triggered_team_first_starting_defender_card_minute Nullable(Int32),
    opponent_first_starting_defender_card_minute Nullable(Int32),
    triggered_team_last_starting_defender_card_minute Nullable(Int32),
    opponent_last_starting_defender_card_minute Nullable(Int32),
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_foul_parity (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_abs_fouls_committed_delta Int32,
    match_total_fouls_committed Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    abs_fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_foul_heavy_stalemate (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_target_home_score Int32,
    trigger_threshold_target_away_score Int32,
    trigger_threshold_min_combined_fouls Int32,
    match_total_fouls_committed Int32,
    match_total_fouls_above_threshold Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_asymmetric_fouls (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_triggered_team_fouls_share_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    match_total_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_fouls_share_above_threshold_pct Float32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_asymmetric_aggression (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_fouls_multiplier Float32,
    trigger_threshold_max_card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    match_total_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_fouls_multiplier Float32,
    fouls_multiplier_above_threshold Float32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_discipline_dominance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_win_margin Int32,
    trigger_threshold_min_fouls_committed_delta Int32,
    trigger_threshold_min_duels_won_delta Int32,
    trigger_threshold_min_card_count_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    win_margin Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    match_total_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    match_total_duels_won Int32,
    duels_won_delta Int32,
    triggered_team_duel_wins_share_pct Float32,
    opponent_duel_wins_share_pct Float32,
    duel_wins_share_delta_pct Float32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_the_disciplined_siege (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_triggered_team_possession_pct Float32,
    trigger_threshold_min_opponent_fouls_committed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    match_total_fouls_committed Int32,
    fouls_committed_delta Int32,
    opponent_fouls_above_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_share_delta_pct Float32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    match_total_cards Int32,
    match_total_yellow_cards Int32,
    match_total_red_cards Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_discipline_cards_card_heavy_substitutions (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_substitute_yellow_carded_players Int32,
    match_distinct_substitute_yellow_carded_players Int32,
    match_distinct_substitute_yellow_carded_players_above_threshold Int32,
    home_distinct_substitute_yellow_carded_players Int32,
    away_distinct_substitute_yellow_carded_players Int32,
    triggered_team_distinct_substitute_yellow_carded_players Int32,
    opponent_distinct_substitute_yellow_carded_players Int32,
    distinct_substitute_yellow_carded_players_delta Int32,
    triggered_team_substitute_yellow_card_events Int32,
    opponent_substitute_yellow_card_events Int32,
    substitute_yellow_card_events_delta Int32,
    triggered_team_first_substitute_yellow_card_minute Nullable(Int32),
    opponent_first_substitute_yellow_card_minute Nullable(Int32),
    triggered_team_substitute_yellow_carded_share_pct Float32,
    opponent_substitute_yellow_carded_share_pct Float32,
    substitute_yellow_carded_share_delta_pct Float32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
