-- Signal tables for entity=team, family=creativity, subfamily=playmaking

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_total_fluidity (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_key_pass_players Int32,
    triggered_team_distinct_key_pass_players Int32,
    triggered_team_distinct_key_pass_players_above_threshold Int32,
    opponent_distinct_key_pass_players Int32,
    distinct_key_pass_players_delta Int32,
    triggered_team_total_key_passes Int32,
    opponent_total_key_passes Int32,
    total_key_passes_delta Int32,
    triggered_team_key_passes_per_creator Float32,
    opponent_key_passes_per_creator Float32,
    key_passes_per_creator_delta Float32,
    triggered_team_multi_key_pass_creators Int32,
    opponent_multi_key_pass_creators Int32,
    multi_key_pass_creators_delta Int32,
    triggered_team_top_creator_key_passes Int32,
    opponent_top_creator_key_passes Int32,
    top_creator_key_passes_delta Int32,
    triggered_team_top_creator_share_pct Float32,
    opponent_top_creator_share_pct Float32,
    top_creator_share_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_unassisted_goals (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_unassisted_solo_goals Int32,
    trigger_threshold_max_assists_on_solo_goals Int32,
    triggered_team_unassisted_solo_goals Int32,
    opponent_unassisted_solo_goals Int32,
    unassisted_solo_goals_delta Int32,
    triggered_team_unassisted_dribble_goals Int32,
    opponent_unassisted_dribble_goals Int32,
    unassisted_dribble_goals_delta Int32,
    triggered_team_unassisted_long_shot_goals Int32,
    opponent_unassisted_long_shot_goals Int32,
    unassisted_long_shot_goals_delta Int32,
    triggered_team_unassisted_non_own_goals Int32,
    opponent_unassisted_non_own_goals Int32,
    unassisted_non_own_goals_delta Int32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_unassisted_solo_goal_share_of_non_own_goals_pct Float32,
    opponent_unassisted_solo_goal_share_of_non_own_goals_pct Float32,
    unassisted_solo_goal_share_of_non_own_goals_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_big_chance_monopoly (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_big_chances Int32,
    trigger_threshold_max_opponent_big_chances Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    big_chances_delta Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    big_chances_missed_delta Int32,
    triggered_team_big_chances_converted Int32,
    opponent_big_chances_converted Int32,
    big_chances_converted_delta Int32,
    triggered_team_big_chance_conversion_pct Float32,
    opponent_big_chance_conversion_pct Float32,
    big_chance_conversion_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_clean_sheet_flag Int8,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_chance_barrage (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_key_passes Int32,
    triggered_team_key_passes Int32,
    opponent_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_expected_assists Float32,
    opponent_expected_assists Float32,
    expected_assists_delta Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_chance_conversion_pct Float32,
    opponent_chance_conversion_pct Float32,
    chance_conversion_delta_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    opposition_box_touches_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_crossing_clinic (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_successful_crosses Int32,
    triggered_team_successful_crosses Int32,
    opponent_successful_crosses Int32,
    successful_crosses_delta Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    cross_attempts_delta Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    cross_accuracy_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_cross_share_of_passes_pct Float32,
    opponent_cross_share_of_passes_pct Float32,
    cross_share_of_passes_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_crosses_per_shot Float32,
    opponent_crosses_per_shot Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_dribbling_exhibition (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_successful_dribbles Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    successful_dribbles_delta Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    dribble_attempts_delta Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    dribble_success_delta_pct Float32,
    triggered_team_successful_dribble_share_pct Float32,
    opponent_successful_dribble_share_pct Float32,
    triggered_team_key_passes Int32,
    opponent_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_expected_assists Float32,
    opponent_expected_assists Float32,
    expected_assists_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    opposition_box_touches_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_unproductive_flair (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_successful_dribbles Int32,
    trigger_threshold_max_goals Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    successful_dribbles_delta Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    dribble_attempts_delta Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    dribble_success_delta_pct Float32,
    triggered_team_successful_dribble_share_pct Float32,
    opponent_successful_dribble_share_pct Float32,
    triggered_team_key_passes Int32,
    opponent_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_expected_assists Float32,
    opponent_expected_assists Float32,
    expected_assists_delta Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    opposition_box_touches_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold.sig_team_creativity_playmaking_final_third_siege (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_successful_final_third_passes Int32,
    triggered_team_successful_final_third_passes Int32,
    opponent_successful_final_third_passes Int32,
    successful_final_third_passes_delta Int32,
    triggered_team_final_third_pass_share_pct Float32,
    opponent_final_third_pass_share_pct Float32,
    triggered_team_key_passes Int32,
    opponent_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_expected_assists Float32,
    opponent_expected_assists Float32,
    expected_assists_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    opposition_box_touches_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
