-- Signal tables for entity=team, family=shooting, subfamily=goals

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_shooting_gallery (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_total_shots Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_no_shots_allowed (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_opponent_shots_on_target Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_clean_sheet_flag Int8,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_shot_on_target_monopoly (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_on_target Int32,
    trigger_threshold_max_opponent_shots_on_target Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_clean_sheet_flag Int8,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_sustained_barrage (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_window_shots Int32,
    trigger_window_minutes Int32,
    triggered_team_shots_in_trigger_window Int32,
    opponent_shots_in_trigger_window Int32,
    shots_in_trigger_window_delta Int32,
    trigger_window_start_effective_minute Int32,
    trigger_window_end_effective_minute Int32,
    triggered_team_first_shot_in_trigger_window_effective_minute Int32,
    triggered_team_last_shot_in_trigger_window_effective_minute Int32,
    triggered_team_shots_on_target_in_trigger_window Int32,
    opponent_shots_on_target_in_trigger_window Int32,
    triggered_team_on_target_ratio_in_trigger_window_pct Float32,
    opponent_on_target_ratio_in_trigger_window_pct Float32,
    on_target_ratio_in_trigger_window_delta_pct Float32,
    triggered_team_xg_in_trigger_window Float32,
    opponent_xg_in_trigger_window Float32,
    xg_in_trigger_window_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_sustained_second_half_siege (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_second_half_shots Int32,
    trigger_threshold_required_half_minutes Int32,
    has_first_half_period_row_flag Int8,
    has_second_half_period_row_flag Int8,
    triggered_team_shots_first_half Int32,
    triggered_team_shots_second_half Int32,
    opponent_shots_first_half Int32,
    opponent_shots_second_half Int32,
    first_half_shots_delta Int32,
    second_half_shots_delta Int32,
    triggered_team_second_half_shot_share_pct Float32,
    opponent_second_half_shot_share_pct Float32,
    second_half_shot_share_delta_pct Float32,
    triggered_team_shots_on_target_second_half Int32,
    opponent_shots_on_target_second_half Int32,
    shots_on_target_second_half_delta Int32,
    triggered_team_on_target_ratio_second_half_pct Float32,
    opponent_on_target_ratio_second_half_pct Float32,
    on_target_ratio_second_half_delta_pct Float32,
    triggered_team_xg_second_half Float32,
    opponent_xg_second_half Float32,
    xg_second_half_delta Float32,
    triggered_team_xg_per_shot_second_half Float32,
    opponent_xg_per_shot_second_half Float32,
    xg_per_shot_second_half_delta Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_early_blitz (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals_first_15 Int32,
    trigger_threshold_window_end_minute Int32,
    triggered_team_goals_first_15 Int32,
    opponent_goals_first_15 Int32,
    goals_first_15_delta Int32,
    triggered_team_first_goal_minute_first_15 Int32,
    triggered_team_first_goal_added_time_first_15 Int32,
    triggered_team_first_goal_effective_minute_first_15 Int32,
    triggered_team_second_goal_minute_first_15 Int32,
    triggered_team_second_goal_added_time_first_15 Int32,
    triggered_team_second_goal_effective_minute_first_15 Int32,
    minutes_between_first_two_goals_first_15 Int32,
    triggered_team_goals_first_15_above_threshold Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_half_time_talk_impact (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals_first_10_second_half Int32,
    trigger_threshold_second_half_window_start_minute Int32,
    trigger_threshold_second_half_window_end_minute Int32,
    triggered_team_goals_first_10_second_half Int32,
    opponent_goals_first_10_second_half Int32,
    goals_first_10_second_half_delta Int32,
    triggered_team_first_goal_minute_first_10_second_half Int32,
    triggered_team_first_goal_added_time_first_10_second_half Int32,
    triggered_team_first_goal_effective_minute_first_10_second_half Int32,
    triggered_team_second_goal_minute_first_10_second_half Int32,
    triggered_team_second_goal_added_time_first_10_second_half Int32,
    triggered_team_second_goal_effective_minute_first_10_second_half Int32,
    minutes_between_first_two_goals_first_10_second_half Int32,
    triggered_team_goals_first_10_second_half_above_threshold Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_late_surge_goals (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals_after_80 Int32,
    trigger_threshold_min_effective_minute Int32,
    triggered_team_goals_after_80 Int32,
    opponent_goals_after_80 Int32,
    goals_after_80_delta Int32,
    triggered_team_first_goal_minute_after_80 Int32,
    triggered_team_first_goal_added_time_after_80 Int32,
    triggered_team_first_goal_effective_minute_after_80 Int32,
    triggered_team_second_goal_minute_after_80 Int32,
    triggered_team_second_goal_added_time_after_80 Int32,
    triggered_team_second_goal_effective_minute_after_80 Int32,
    minutes_between_first_two_goals_after_80 Int32,
    triggered_team_goals_after_80_above_threshold Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_late_game_salvage (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goal_effective_minute Int32,
    trigger_threshold_min_late_salvage_goals Int32,
    triggered_team_late_salvage_goals Int32,
    triggered_team_late_tying_goals Int32,
    triggered_team_late_winning_goals Int32,
    opponent_late_salvage_goals Int32,
    late_salvage_goals_delta Int32,
    triggered_team_first_late_salvage_goal_minute Int32,
    triggered_team_first_late_salvage_goal_added_time Int32,
    triggered_team_first_late_salvage_goal_effective_minute Int32,
    triggered_team_first_late_salvage_goal_type LowCardinality(String),
    triggered_team_score_before_first_late_salvage_goal Int32,
    opponent_score_before_first_late_salvage_goal Int32,
    triggered_team_score_after_first_late_salvage_goal Int32,
    opponent_score_after_first_late_salvage_goal Int32,
    triggered_team_late_salvage_goals_above_threshold Int32,
    triggered_team_final_result_points Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_rapid_response_goal (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_response_minutes Int32,
    trigger_threshold_min_rapid_response_goals Int32,
    triggered_team_rapid_response_goals Int32,
    opponent_rapid_response_goals Int32,
    rapid_response_goals_delta Int32,
    triggered_team_first_conceded_goal_minute_before_response Int32,
    triggered_team_first_conceded_goal_added_time_before_response Int32,
    triggered_team_first_conceded_goal_effective_minute_before_response Int32,
    triggered_team_first_response_goal_minute Int32,
    triggered_team_first_response_goal_added_time Int32,
    triggered_team_first_response_goal_effective_minute Int32,
    minutes_to_first_response_goal Int32,
    triggered_team_average_response_time_minutes Float32,
    opponent_average_response_time_minutes Float32,
    average_response_time_delta_minutes Float32,
    rapid_response_window_margin_minutes Int32,
    triggered_team_rapid_response_goals_above_threshold Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_rapid_double_salvo (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_double_salvo_window_minutes Int32,
    trigger_threshold_min_rapid_double_salvo_pairs Int32,
    triggered_team_rapid_double_salvo_pairs Int32,
    opponent_rapid_double_salvo_pairs Int32,
    rapid_double_salvo_pairs_delta Int32,
    triggered_team_first_salvo_first_goal_minute Int32,
    triggered_team_first_salvo_first_goal_added_time Int32,
    triggered_team_first_salvo_first_goal_effective_minute Int32,
    triggered_team_first_salvo_second_goal_minute Int32,
    triggered_team_first_salvo_second_goal_added_time Int32,
    triggered_team_first_salvo_second_goal_effective_minute Int32,
    minutes_between_first_salvo_goals Int32,
    triggered_team_smallest_salvo_gap_minutes Int32,
    triggered_team_average_salvo_gap_minutes Float32,
    opponent_average_salvo_gap_minutes Float32,
    average_salvo_gap_delta_minutes Float32,
    triggered_team_last_salvo_second_goal_effective_minute Int32,
    rapid_double_salvo_window_margin_minutes Int32,
    triggered_team_rapid_double_salvo_pairs_above_threshold Int32,
    triggered_team_goals_final Int32,
    opponent_goals_final Int32,
    goal_delta_final Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_blank_range (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_xg Float32,
    trigger_required_goals Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_wasteful_box_presence (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_touches_opposition_box Int32,
    trigger_required_goals Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    touches_opposition_box_delta Int32,
    triggered_team_touches_opposition_box_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_conversion_collapse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_on_target Int32,
    trigger_required_goals Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_goal_conversion_pct Float32,
    opponent_goal_conversion_pct Float32,
    goal_conversion_delta_pct Float32,
    triggered_team_goals_per_shot_on_target Float32,
    opponent_goals_per_shot_on_target Float32,
    goals_per_shot_on_target_delta Float32,
    triggered_team_unconverted_shots_on_target Int32,
    opponent_unconverted_shots_on_target Int32,
    unconverted_shots_on_target_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_shot_shy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_shots_per_half Int32,
    triggered_half_without_shot LowCardinality(String),
    triggered_team_shots_first_half Int32,
    triggered_team_shots_second_half Int32,
    opponent_shots_first_half Int32,
    opponent_shots_second_half Int32,
    triggered_team_zero_shot_first_half_flag Int8,
    triggered_team_zero_shot_second_half_flag Int8,
    opponent_zero_shot_first_half_flag Int8,
    opponent_zero_shot_second_half_flag Int8,
    half_shot_gap_first_half Int32,
    half_shot_gap_second_half Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_zero_shot_half (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_shots_per_half Int32,
    trigger_threshold_required_half_minutes Int32,
    triggered_half_without_shot LowCardinality(String),
    has_first_half_period_row_flag Int8,
    has_second_half_period_row_flag Int8,
    triggered_team_shots_first_half Int32,
    triggered_team_shots_second_half Int32,
    opponent_shots_first_half Int32,
    opponent_shots_second_half Int32,
    triggered_team_zero_shot_first_half_flag Int8,
    triggered_team_zero_shot_second_half_flag Int8,
    opponent_zero_shot_first_half_flag Int8,
    opponent_zero_shot_second_half_flag Int8,
    half_shot_gap_first_half Int32,
    half_shot_gap_second_half Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_dead_ball_specialists (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_dead_ball_goals Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_dead_ball_goals Int32,
    opponent_dead_ball_goals Int32,
    dead_ball_goals_delta Int32,
    triggered_team_corner_goals Int32,
    opponent_corner_goals Int32,
    corner_goals_delta Int32,
    triggered_team_free_kick_goals Int32,
    opponent_free_kick_goals Int32,
    free_kick_goals_delta Int32,
    triggered_team_set_piece_goals Int32,
    opponent_set_piece_goals Int32,
    set_piece_goals_delta Int32,
    triggered_team_dead_ball_goal_share_pct Float32,
    opponent_dead_ball_goal_share_pct Float32,
    dead_ball_goal_share_delta_pct Float32,
    triggered_team_dead_ball_shots Int32,
    opponent_dead_ball_shots Int32,
    triggered_team_dead_ball_xg Float32,
    opponent_dead_ball_xg Float32,
    dead_ball_xg_delta Float32,
    triggered_team_dead_ball_goals_per_shot Float32,
    opponent_dead_ball_goals_per_shot Float32,
    dead_ball_goals_per_shot_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_set_play_xg Float32,
    opponent_set_play_xg Float32,
    set_play_xg_delta Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_set_piece_masterclass (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_corner_goals Int32,
    trigger_threshold_min_free_kick_goals Int32,
    trigger_threshold_min_penalty_goals Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_corner_goals Int32,
    opponent_corner_goals Int32,
    corner_goals_delta Int32,
    triggered_team_free_kick_goals Int32,
    opponent_free_kick_goals Int32,
    free_kick_goals_delta Int32,
    triggered_team_penalty_goals Int32,
    opponent_penalty_goals Int32,
    penalty_goals_delta Int32,
    triggered_team_set_piece_components_hit Int32,
    opponent_set_piece_components_hit Int32,
    set_piece_components_hit_delta Int32,
    triggered_team_corner_free_kick_penalty_goals Int32,
    opponent_corner_free_kick_penalty_goals Int32,
    corner_free_kick_penalty_goals_delta Int32,
    triggered_team_corner_free_kick_penalty_goal_share_pct Float32,
    opponent_corner_free_kick_penalty_goal_share_pct Float32,
    corner_free_kick_penalty_goal_share_delta_pct Float32,
    triggered_team_corner_free_kick_penalty_shots Int32,
    opponent_corner_free_kick_penalty_shots Int32,
    triggered_team_corner_free_kick_penalty_expected_goals Float32,
    opponent_corner_free_kick_penalty_expected_goals Float32,
    corner_free_kick_penalty_expected_goals_delta Float32,
    triggered_team_corner_free_kick_penalty_goals_per_shot Float32,
    opponent_corner_free_kick_penalty_goals_per_shot Float32,
    corner_free_kick_penalty_goals_per_shot_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_set_play_expected_goals Float32,
    opponent_set_play_expected_goals Float32,
    set_play_expected_goals_delta Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_shot_accuracy_collapse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_total_shots Int32,
    trigger_threshold_max_shot_accuracy_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_shots_off_target Int32,
    opponent_shots_off_target Int32,
    shots_off_target_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_shot_conversion_pct Float32,
    opponent_shot_conversion_pct Float32,
    shot_conversion_delta_pct Float32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_expected_goals_per_shot Float32,
    opponent_expected_goals_per_shot Float32,
    expected_goals_per_shot_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_long_range_barrage (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_outside_box Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    shots_outside_box_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_outside_box_shot_share_pct Float32,
    opponent_outside_box_shot_share_pct Float32,
    outside_box_shot_share_delta_pct Float32,
    triggered_team_outside_box_shots_on_target Int32,
    opponent_outside_box_shots_on_target Int32,
    triggered_team_outside_box_shot_accuracy_pct Float32,
    opponent_outside_box_shot_accuracy_pct Float32,
    outside_box_shot_accuracy_delta_pct Float32,
    triggered_team_outside_box_goals Int32,
    opponent_outside_box_goals Int32,
    triggered_team_outside_box_xg Float32,
    opponent_outside_box_xg Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_box_siege (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_inside_box Int32,
    triggered_team_shots_inside_box Int32,
    opponent_shots_inside_box Int32,
    shots_inside_box_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_inside_box_shot_share_pct Float32,
    opponent_inside_box_shot_share_pct Float32,
    inside_box_shot_share_delta_pct Float32,
    triggered_team_inside_box_shots_on_target Int32,
    opponent_inside_box_shots_on_target Int32,
    triggered_team_inside_box_shot_accuracy_pct Float32,
    opponent_inside_box_shot_accuracy_pct Float32,
    inside_box_shot_accuracy_delta_pct Float32,
    triggered_team_inside_box_goals Int32,
    opponent_inside_box_goals Int32,
    triggered_team_inside_box_xg Float32,
    opponent_inside_box_xg Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_efficiency_peak (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_max_total_shots_exclusive Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_goals_per_total_shot Float32,
    opponent_goals_per_total_shot Float32,
    goals_per_total_shot_delta Float32,
    triggered_team_goal_conversion_pct Float32,
    opponent_goal_conversion_pct Float32,
    goal_conversion_delta_pct Float32,
    triggered_team_goals_per_shot_on_target Float32,
    opponent_goals_per_shot_on_target Float32,
    goals_per_shot_on_target_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    goals_above_threshold Int32,
    total_shots_below_exclusive_threshold Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_ruthless_efficiency (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_max_shots_on_target Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_goals_per_shot_on_target Float32,
    opponent_goals_per_shot_on_target Float32,
    goals_per_shot_on_target_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_clinical_finishing_streak (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_on_target Int32,
    trigger_threshold_goal_conversion_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_goal_conversion_pct Float32,
    opponent_goal_conversion_pct Float32,
    goal_conversion_delta_pct Float32,
    triggered_team_goals_per_shot_on_target Float32,
    opponent_goals_per_shot_on_target Float32,
    goals_per_shot_on_target_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_big_chance_efficiency (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_big_chances Int32,
    trigger_threshold_required_big_chances_missed Int32,
    trigger_threshold_big_chance_conversion_pct Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    big_chances_delta Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    big_chances_missed_delta Int32,
    triggered_team_big_chances_converted Int32,
    opponent_big_chances_converted Int32,
    big_chances_converted_delta Int32,
    triggered_team_big_chance_conversion_pct Float32,
    opponent_big_chance_conversion_pct Float32,
    big_chance_conversion_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_shot_accuracy_pct Float32,
    opponent_shot_accuracy_pct Float32,
    shot_accuracy_delta_pct Float32,
    triggered_team_goal_conversion_pct Float32,
    opponent_goal_conversion_pct Float32,
    goal_conversion_delta_pct Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    touches_opposition_box_delta Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_defensive_scoring_unit (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_defender_goal_scorers Int32,
    triggered_team_distinct_defender_goal_scorers Int32,
    opponent_distinct_defender_goal_scorers Int32,
    distinct_defender_goal_scorers_delta Int32,
    triggered_team_defender_non_own_goals Int32,
    opponent_defender_non_own_goals Int32,
    defender_non_own_goals_delta Int32,
    triggered_team_top_defender_scorer_goals Int32,
    opponent_top_defender_scorer_goals Int32,
    top_defender_scorer_goals_delta Int32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_defender_goal_share_pct Float32,
    opponent_defender_goal_share_pct Float32,
    defender_goal_share_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_no_striker_needed (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_non_own_goals Int32,
    trigger_threshold_required_forward_non_own_goals Int32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_midfielder_non_own_goals Int32,
    opponent_midfielder_non_own_goals Int32,
    midfielder_non_own_goals_delta Int32,
    triggered_team_defender_non_own_goals Int32,
    opponent_defender_non_own_goals Int32,
    defender_non_own_goals_delta Int32,
    triggered_team_midfielder_defender_non_own_goals Int32,
    opponent_midfielder_defender_non_own_goals Int32,
    midfielder_defender_non_own_goals_delta Int32,
    triggered_team_forward_non_own_goals Int32,
    opponent_forward_non_own_goals Int32,
    forward_non_own_goals_delta Int32,
    triggered_team_other_or_unknown_non_own_goals Int32,
    opponent_other_or_unknown_non_own_goals Int32,
    other_or_unknown_non_own_goals_delta Int32,
    triggered_team_distinct_midfielder_defender_goal_scorers Int32,
    opponent_distinct_midfielder_defender_goal_scorers Int32,
    distinct_midfielder_defender_goal_scorers_delta Int32,
    triggered_team_distinct_forward_goal_scorers Int32,
    opponent_distinct_forward_goal_scorers Int32,
    distinct_forward_goal_scorers_delta Int32,
    triggered_team_midfielder_defender_goal_share_pct Float32,
    opponent_midfielder_defender_goal_share_pct Float32,
    midfielder_defender_goal_share_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_shared_scoring (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_goal_scorers Int32,
    triggered_team_distinct_goal_scorers Int32,
    opponent_distinct_goal_scorers Int32,
    distinct_goal_scorers_delta Int32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_single_goal_scorers Int32,
    opponent_single_goal_scorers Int32,
    single_goal_scorers_delta Int32,
    triggered_team_multi_goal_scorers Int32,
    opponent_multi_goal_scorers Int32,
    multi_goal_scorers_delta Int32,
    triggered_team_top_scorer_goals Int32,
    opponent_top_scorer_goals Int32,
    top_scorer_goals_delta Int32,
    triggered_team_top_scorer_goal_share_pct Float32,
    opponent_top_scorer_goal_share_pct Float32,
    top_scorer_goal_share_delta_pct Float32,
    triggered_team_scorer_spread_pct Float32,
    opponent_scorer_spread_pct Float32,
    scorer_spread_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_bench_goals_impact (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_substitute_non_own_goals Int32,
    triggered_team_substitute_non_own_goals Int32,
    opponent_substitute_non_own_goals Int32,
    substitute_non_own_goals_delta Int32,
    triggered_team_distinct_substitute_goal_scorers Int32,
    opponent_distinct_substitute_goal_scorers Int32,
    distinct_substitute_goal_scorers_delta Int32,
    triggered_team_top_substitute_scorer_goals Int32,
    opponent_top_substitute_scorer_goals Int32,
    top_substitute_scorer_goals_delta Int32,
    triggered_team_first_substitute_goal_effective_minute Int32,
    opponent_first_substitute_goal_effective_minute Int32,
    triggered_team_last_substitute_goal_effective_minute Int32,
    opponent_last_substitute_goal_effective_minute Int32,
    triggered_team_substitute_goal_share_pct Float32,
    opponent_substitute_goal_share_pct Float32,
    substitute_goal_share_delta_pct Float32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_clinical_bench_impact (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_substitute_non_own_goals Int32,
    trigger_threshold_min_substitute_goal_share_pct Float32,
    triggered_team_substitute_non_own_goals Int32,
    opponent_substitute_non_own_goals Int32,
    substitute_non_own_goals_delta Int32,
    triggered_team_distinct_substitute_goal_scorers Int32,
    opponent_distinct_substitute_goal_scorers Int32,
    distinct_substitute_goal_scorers_delta Int32,
    triggered_team_top_substitute_scorer_goals Int32,
    opponent_top_substitute_scorer_goals Int32,
    top_substitute_scorer_goals_delta Int32,
    triggered_team_first_substitute_goal_effective_minute Int32,
    opponent_first_substitute_goal_effective_minute Int32,
    triggered_team_last_substitute_goal_effective_minute Int32,
    opponent_last_substitute_goal_effective_minute Int32,
    triggered_team_substitute_goal_share_pct Float32,
    opponent_substitute_goal_share_pct Float32,
    substitute_goal_share_delta_pct Float32,
    triggered_team_non_own_goals Int32,
    opponent_non_own_goals Int32,
    non_own_goals_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_xg_overperformance_team (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_max_expected_goals Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_delta Float32,
    goals_above_threshold Int32,
    expected_goals_below_threshold Float32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_goal_conversion_pct Float32,
    opponent_goal_conversion_pct Float32,
    goal_conversion_delta_pct Float32,
    triggered_team_goals_per_shot_on_target Float32,
    opponent_goals_per_shot_on_target Float32,
    goals_per_shot_on_target_delta Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_offensive_masterclass (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_xg_per_shot Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_high_quality_only (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_xg_per_shot Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_woodwork_frustration_team (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_woodwork Int32,
    match_total_shots_woodwork Int32,
    triggered_team_shots_woodwork Int32,
    opponent_shots_woodwork Int32,
    shots_woodwork_delta Int32,
    triggered_team_shots_woodwork_share_pct Float32,
    opponent_shots_woodwork_share_pct Float32,
    shots_woodwork_share_delta_pct Float32,
    triggered_team_shots_woodwork_above_threshold Int32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_shooting_goals_expected_goal_dominance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_triggered_team_xg Float32,
    trigger_threshold_max_opponent_xg Float32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_xg_above_threshold Float32,
    opponent_xg_below_threshold Float32,
    trigger_clearance_xg Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_on_target_ratio_pct Float32,
    opponent_on_target_ratio_pct Float32,
    on_target_ratio_delta_pct Float32,
    triggered_team_xg_per_shot Float32,
    opponent_xg_per_shot Float32,
    xg_per_shot_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_clean_sheet_flag Int8,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
