-- Signal tables for entity=player, family=possession, subfamily=passing

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_flawless_distributor (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_pass_attempts Int32,
    trigger_threshold_pass_accuracy_pct Float32,
    triggered_player_pass_attempts Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    triggered_player_vs_team_pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_keeper_distributor (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_accurate_short_passes Int32,
    triggered_player_accurate_short_passes_proxy Int32,
    triggered_player_short_pass_attempts_proxy Int32,
    triggered_player_short_pass_accuracy_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_long_ball_attempts Int32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_accurate_passes_pct Float32,
    triggered_player_short_pass_share_of_accurate_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_safe_outlet (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_pass_attempts Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_long_ball_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_long_balls_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_keeper_launch_heavy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_long_balls_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_target_man_aerials (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_minutes_played Int32,
    triggered_player_aerial_duels_won Int32,
    triggered_player_aerial_duel_attempts Int32,
    triggered_player_aerial_duel_success_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_total_shots Int32,
    triggered_player_expected_goals Float32,
    triggered_team_aerials_won Int32,
    opponent_aerials_won Int32,
    triggered_team_aerial_attempts Int32,
    opponent_aerial_attempts Int32,
    triggered_team_aerial_success_pct Float32,
    opponent_aerial_success_pct Float32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_aerials_won_pct Float32,
    player_share_of_team_long_ball_attempts_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_accurate_long_range (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_long_balls_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_switch_expert (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_long_ball_attempts Int32,
    triggered_player_successful_switches_proxy Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_successful_switches_proxy Int32,
    opponent_successful_switches_proxy Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_switches_proxy_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_cross_heavy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_crosses_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_volume_crosser (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_crosses_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_unsuccessful_crosser (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_total_passes Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_crosses_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_creative_hub (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_final_third_engine (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_passes_final_third Int32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_half_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_creative_monopoly (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_chances_created Int32,
    triggered_team_total_chances_created Int32,
    player_share_of_team_chances_created_pct Float32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_corner_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_corner_chances_created Int32,
    triggered_player_corner_assisted_shots_on_target Int32,
    triggered_player_corner_assisted_shot_expected_goals Float32,
    triggered_player_corner_assisted_goals Int32,
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_corner_shots Int32,
    opponent_corner_shots Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_triggered_team_corner_shots_pct Float32,
    player_share_of_team_crosses_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_deadball_creator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_indirect_free_kick_big_chances_created Int32,
    triggered_player_indirect_free_kick_chances_created Int32,
    triggered_player_indirect_free_kick_assisted_shots_on_target Int32,
    triggered_player_indirect_free_kick_assisted_shot_expected_goals Float32,
    triggered_player_indirect_free_kick_assisted_goals Int32,
    triggered_player_expected_assists Float32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_indirect_free_kick_big_chances Int32,
    opponent_indirect_free_kick_big_chances Int32,
    triggered_team_indirect_free_kick_chances Int32,
    opponent_indirect_free_kick_chances Int32,
    triggered_team_set_piece_shots Int32,
    opponent_set_piece_shots Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_triggered_team_indirect_free_kick_big_chances_pct Float32,
    player_share_of_triggered_team_indirect_free_kick_chances_pct Float32,
    player_share_of_team_crosses_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_xa_underperformer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_expected_assists Float32,
    triggered_player_assists Int32,
    triggered_player_chances_created Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_xa_overperformer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_expected_assists Float32,
    triggered_player_assists Int32,
    triggered_player_chances_created Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_impact_sub_passing (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_substitution_time Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes_per_minute Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    player_share_of_team_passes_pct Float32,
    triggered_player_vs_team_pass_accuracy_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_high_turnover_risk (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_possession_losses Int32,
    triggered_player_failed_passes Int32,
    triggered_player_failed_dribbles Int32,
    triggered_player_duels_lost Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_successful_dribbles Int32,
    triggered_player_dribble_attempts Int32,
    triggered_player_dribble_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_dribbles_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_high_risk_passer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_big_chances_created Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_big_chances_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_under_pressure_expert (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_pass_accuracy_above_threshold_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_was_fouled Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_player_vs_team_pass_accuracy_delta_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_fouls Int32,
    opponent_fouls Int32,
    triggered_team_press_actions Int32,
    opponent_press_actions Int32,
    opponent_press_actions_per_100_triggered_passes Float32,
    press_actions_delta Int32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_dribble_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_successful_dribbles Int32,
    triggered_player_dribble_attempts Int32,
    triggered_player_failed_dribbles Int32,
    triggered_player_dribble_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_dribbles_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_perfect_dribbler (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_successful_dribbles Int32,
    triggered_player_dribble_attempts Int32,
    triggered_player_failed_dribbles Int32,
    triggered_player_dribble_success_rate_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_dribbles_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_isolated_target (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_position_id Nullable(Int32),
    triggered_player_usual_playing_position_id Nullable(Int32),
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_touches_per90 Float32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_midfield_general (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_middle_third_touches_proxy Int32,
    triggered_player_total_touches Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_century_touches (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_total_touches Int32,
    triggered_player_touches_per90 Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_overloaded_possession (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_total_touches Int32,
    triggered_player_touches_per90 Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_back_pass_heavy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_backward_sideways_passes_proxy Int32,
    triggered_player_total_passes Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_backward_sideways_pass_share_pct Float32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_deep_playmaker (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_accurate_passes Int32,
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_non_final_third_passes_proxy Int32,
    triggered_player_non_final_third_pass_share_pct Float32,
    triggered_player_touches Int32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_accurate_passes_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_recycling_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_non_final_third_passes_proxy Int32,
    triggered_player_non_final_third_pass_share_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_defensive_actions Int32,
    triggered_player_recoveries Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_redundant_possession (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_total_passes Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_non_final_third_passes_proxy Int32,
    triggered_player_non_final_third_pass_share_pct Float32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_one_touch_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_total_passes Int32,
    trigger_threshold_max_touches_per_pass Float32,
    triggered_player_total_touches Int32,
    triggered_player_total_passes Int32,
    triggered_player_touches_per_pass Float32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_accurate_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_midfield_workhorse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_total_touches Int32,
    triggered_player_recoveries Int32,
    triggered_player_defensive_actions Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_own_half_pass_share_pct Float32,
    opponent_own_half_pass_share_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_vertical_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_forward_successful_passes_proxy Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_forward_successful_pass_share_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_possession_passing_box_penetrator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_touches_opposition_box Int32,
    triggered_player_total_touches Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);
