-- Signal tables for entity=team, family=discipline, subfamily=cards

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_collective_aggression (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_fouls_committed Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_above_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_aggression_spike (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_foul_multiplier Float32,
    trigger_threshold_min_first_half_fouls Int32,
    triggered_team_fouls_first_half Int32,
    triggered_team_fouls_second_half Int32,
    opponent_fouls_first_half Int32,
    opponent_fouls_second_half Int32,
    triggered_team_fouls_second_half_minus_first_half Int32,
    opponent_fouls_second_half_minus_first_half Int32,
    foul_escalation_delta Int32,
    triggered_team_second_half_to_first_half_foul_ratio Nullable(Float32),
    opponent_second_half_to_first_half_foul_ratio Nullable(Float32),
    foul_ratio_delta Nullable(Float32),
    triggered_team_second_half_fouls_share_pct Nullable(Float32),
    opponent_second_half_fouls_share_pct Nullable(Float32),
    second_half_fouls_share_delta_pct Nullable(Float32),
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_aggression_drop_off (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_first_half_fouls Int32,
    trigger_threshold_max_second_half_fouls Int32,
    triggered_team_fouls_first_half Int32,
    triggered_team_fouls_second_half Int32,
    opponent_fouls_first_half Int32,
    opponent_fouls_second_half Int32,
    triggered_team_fouls_first_half_minus_second_half Int32,
    opponent_fouls_first_half_minus_second_half Int32,
    foul_de_escalation_delta Int32,
    triggered_team_second_half_to_first_half_foul_ratio Nullable(Float32),
    opponent_second_half_to_first_half_foul_ratio Nullable(Float32),
    foul_ratio_delta Nullable(Float32),
    triggered_team_foul_drop_pct Nullable(Float32),
    opponent_foul_drop_pct Nullable(Float32),
    foul_drop_delta_pct Nullable(Float32),
    triggered_team_first_half_fouls_share_pct Nullable(Float32),
    opponent_first_half_fouls_share_pct Nullable(Float32),
    first_half_fouls_share_delta_pct Nullable(Float32),
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_systematic_fouling (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_starting_midfielders Int32,
    trigger_threshold_min_yellow_cards_per_starting_midfielder Int32,
    triggered_team_starting_midfielders Int32,
    opponent_starting_midfielders Int32,
    starting_midfielders_delta Int32,
    triggered_team_starting_midfielders_booked Int32,
    opponent_starting_midfielders_booked Int32,
    starting_midfielders_booked_delta Int32,
    triggered_team_starting_midfielders_booked_share_pct Float32,
    opponent_starting_midfielders_booked_share_pct Nullable(Float32),
    triggered_team_yellow_cards_on_starting_midfielders Int32,
    opponent_yellow_cards_on_starting_midfielders Int32,
    yellow_cards_on_starting_midfielders_delta Int32,
    triggered_team_first_starting_midfielder_yellow_card_minute Nullable(Int32),
    opponent_first_starting_midfielder_yellow_card_minute Nullable(Int32),
    triggered_team_last_starting_midfielder_yellow_card_minute Nullable(Int32),
    opponent_last_starting_midfielder_yellow_card_minute Nullable(Int32),
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_midfield_enforcement (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_central_midfielder_fouls_committed Int32,
    triggered_team_central_midfielders Int32,
    opponent_central_midfielders Int32,
    central_midfielders_delta Int32,
    triggered_team_central_midfielders_with_fouls Int32,
    opponent_central_midfielders_with_fouls Int32,
    central_midfielders_with_fouls_delta Int32,
    triggered_team_central_midfielder_fouls_committed Int32,
    opponent_central_midfielder_fouls_committed Int32,
    central_midfielder_fouls_committed_delta Int32,
    triggered_team_central_midfielder_fouls_above_threshold Int32,
    triggered_team_central_midfielder_fouls_share_of_team_fouls_pct Float32,
    opponent_central_midfielder_fouls_share_of_team_fouls_pct Nullable(Float32),
    central_midfielder_fouls_share_of_team_fouls_delta_pct Float32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_half_time_talk_fail (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_yellow_cards Int32,
    trigger_window_start_minute Int32,
    trigger_window_end_minute Int32,
    triggered_team_yellow_cards_window Int32,
    opponent_yellow_cards_window Int32,
    yellow_cards_window_delta Int32,
    triggered_team_first_yellow_card_window_minute Int32,
    triggered_team_third_yellow_card_window_minute Int32,
    minutes_from_second_half_start_to_third_yellow Int32,
    triggered_team_score_at_third_yellow Int32,
    opponent_score_at_third_yellow Int32,
    score_margin_at_third_yellow Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    yellow_cards_match_delta Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_early_warning (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_booked_players_early Int32,
    trigger_threshold_booking_minute_exclusive Int32,
    triggered_team_distinct_booked_players_early Int32,
    opponent_distinct_booked_players_early Int32,
    distinct_booked_players_early_delta Int32,
    triggered_team_early_bookings_total Int32,
    opponent_early_bookings_total Int32,
    early_bookings_total_delta Int32,
    triggered_team_first_booking_minute_early Int32,
    opponent_first_booking_minute_early Nullable(Int32),
    triggered_team_third_distinct_booking_minute_early Int32,
    opponent_third_distinct_booking_minute_early Nullable(Int32),
    triggered_team_early_booked_player_share_pct Float32,
    opponent_early_booked_player_share_pct Float32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_first_half_frenzy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_cards_first_half Int32,
    trigger_window_start_minute Int32,
    trigger_window_end_minute Int32,
    triggered_team_cards_first_half Int32,
    opponent_cards_first_half Int32,
    cards_first_half_delta Int32,
    triggered_team_cards_first_half_above_threshold Int32,
    triggered_team_yellow_cards_first_half Int32,
    opponent_yellow_cards_first_half Int32,
    yellow_cards_first_half_delta Int32,
    triggered_team_red_cards_first_half Int32,
    opponent_red_cards_first_half Int32,
    red_cards_first_half_delta Int32,
    triggered_team_first_card_first_half_minute Int32,
    opponent_first_card_first_half_minute Nullable(Int32),
    triggered_team_fourth_card_first_half_minute Int32,
    triggered_team_fourth_card_first_half_added_time Int32,
    triggered_team_fourth_card_first_half_effective_minute Int32,
    opponent_fourth_card_first_half_minute Nullable(Int32),
    opponent_fourth_card_first_half_added_time Nullable(Int32),
    opponent_fourth_card_first_half_effective_minute Nullable(Int32),
    triggered_team_score_at_fourth_card Int32,
    opponent_score_at_fourth_card Int32,
    score_margin_at_fourth_card Int32,
    triggered_team_first_half_cards_share_pct Nullable(Float32),
    opponent_first_half_cards_share_pct Nullable(Float32),
    first_half_cards_share_delta_pct Nullable(Float32),
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    yellow_cards_match_delta Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_the_triple_booking (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_distinct_yellow_carded_players Int32,
    trigger_threshold_rolling_window_minutes Int32,
    triggered_team_booking_window_start_minute Int32,
    triggered_team_booking_window_end_minute Int32,
    triggered_team_third_distinct_yellow_card_minute Int32,
    triggered_team_distinct_yellow_carded_players_in_window Int32,
    opponent_max_distinct_yellow_carded_players_in_window Int32,
    distinct_yellow_carded_players_in_window_delta Int32,
    triggered_team_yellow_card_events_in_window Int32,
    opponent_max_yellow_card_events_in_window Int32,
    yellow_card_events_in_window_delta Int32,
    triggered_team_match_yellow_card_events Int32,
    opponent_match_yellow_card_events Int32,
    match_yellow_card_events_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_cards_per_foul_pct Nullable(Float32),
    opponent_cards_per_foul_pct Nullable(Float32),
    cards_per_foul_delta_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_man_down_resilience (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_red_card_minute Int32,
    triggered_team_first_red_card_minute Int32,
    triggered_team_red_cards_before_60 Int32,
    opponent_red_cards_before_60 Int32,
    red_cards_before_60_delta Int32,
    triggered_team_score_at_first_red Int32,
    opponent_score_at_first_red Int32,
    score_margin_at_first_red Int32,
    triggered_team_goals_after_first_red Int32,
    opponent_goals_after_first_red Int32,
    goals_after_first_red_delta Int32,
    triggered_team_win_margin Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_red_card_neutralizer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_minutes_after_red Int32,
    triggered_team_first_red_card_minute Int32,
    triggered_team_first_red_card_added_time Int32,
    triggered_team_first_red_card_effective_minute Int32,
    triggered_team_neutralizing_goal_minute Int32,
    triggered_team_neutralizing_goal_added_time Int32,
    triggered_team_neutralizing_goal_effective_minute Int32,
    minutes_from_red_to_goal Int32,
    triggered_team_score_at_first_red Int32,
    opponent_score_at_first_red Int32,
    score_margin_at_first_red Int32,
    triggered_team_score_after_neutralizing_goal Int32,
    opponent_score_after_neutralizing_goal Int32,
    score_margin_after_neutralizing_goal Int32,
    score_margin_swing_after_goal Int32,
    triggered_team_neutralizing_goal_scorer_id Nullable(Int32),
    triggered_team_neutralizing_goal_scorer_name Nullable(String),
    triggered_team_neutralizing_goal_is_own_goal UInt8,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    shot_delta Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_man_advantage_collapse (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_opponent_red_cards Int32,
    opponent_first_red_card_minute Int32,
    triggered_team_score_at_opponent_first_red Int32,
    opponent_score_at_opponent_first_red Int32,
    score_margin_at_opponent_first_red Int32,
    triggered_team_estimated_minutes_with_man_advantage Int32,
    triggered_team_goals_after_opponent_first_red Int32,
    opponent_goals_after_opponent_first_red Int32,
    goals_after_opponent_first_red_delta Int32,
    triggered_team_loss_margin Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_card_heavy_defeat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_loss_margin_goals Int32,
    trigger_threshold_min_red_cards_match Int32,
    triggered_team_loss_margin Int32,
    triggered_team_first_red_card_minute Int32,
    opponent_first_red_card_minute Int32,
    triggered_team_score_at_first_red Int32,
    opponent_score_at_first_red Int32,
    score_margin_at_first_red Int32,
    triggered_team_goals_after_first_red Int32,
    opponent_goals_after_first_red Int32,
    goals_after_first_red_delta Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_per_card Nullable(Float32),
    opponent_fouls_per_card Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_penalty_prone (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_penalties_conceded Int32,
    triggered_team_penalties_conceded Int32,
    opponent_penalties_conceded Int32,
    penalties_conceded_delta Int32,
    triggered_team_penalties_awarded Int32,
    opponent_penalties_awarded Int32,
    total_match_penalties_awarded Int32,
    triggered_team_penalties_conceded_scored Int32,
    triggered_team_penalties_conceded_missed Int32,
    opponent_penalties_conceded_scored Int32,
    opponent_penalties_conceded_missed Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_clean_discipline (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_total_cards Int32,
    trigger_threshold_max_fouls_committed Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_below_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_clean_sheet_aggression (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_yellow_cards Int32,
    trigger_threshold_max_opponent_goals Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    yellow_cards_above_threshold Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    triggered_team_win_margin Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    triggered_team_clean_sheet_flag UInt8,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_foul_efficiency (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_fouls_committed Int32,
    trigger_threshold_max_total_cards Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_above_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Float32,
    opponent_cards_per_foul_pct Float32,
    cards_per_foul_delta_pct Float32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_physical_superiority (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_duel_wins_share_pct Float32,
    trigger_threshold_min_fouls_committed Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_duels_total Int32,
    triggered_team_duel_wins_share_pct Float32,
    opponent_duel_wins_share_pct Float32,
    duel_wins_share_delta_pct Float32,
    triggered_team_duel_wins_share_above_threshold_pct Float32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_above_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_cards_per_foul_pct Float32,
    opponent_cards_per_foul_pct Float32,
    cards_per_foul_delta_pct Float32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_zero_card_miracle (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_fouls_committed Int32,
    trigger_threshold_max_yellow_cards Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_above_threshold Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    fouls_committed_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_card_count_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_card_count_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_yellow_cards_per_foul_pct Float32,
    opponent_yellow_cards_per_foul_pct Float32,
    yellow_cards_per_foul_delta_pct Float32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_discipline_meltdown (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_red_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_per_card Nullable(Float32),
    opponent_fouls_per_card Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_total_implosion (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_red_cards_same_half Int32,
    triggered_half LowCardinality(String),
    triggered_team_both_halves_threshold_breach Int8,
    triggered_team_red_cards_first_half Int32,
    triggered_team_red_cards_second_half Int32,
    opponent_red_cards_first_half Int32,
    opponent_red_cards_second_half Int32,
    triggered_team_red_cards_trigger_half Int32,
    opponent_red_cards_trigger_half Int32,
    red_cards_trigger_half_delta Int32,
    triggered_team_yellow_cards_trigger_half Int32,
    opponent_yellow_cards_trigger_half Int32,
    triggered_team_total_cards_trigger_half Int32,
    opponent_total_cards_trigger_half Int32,
    card_count_trigger_half_delta Int32,
    triggered_team_red_cards_match Int32,
    opponent_red_cards_match Int32,
    red_cards_match_delta Int32,
    triggered_team_yellow_cards_match Int32,
    opponent_yellow_cards_match Int32,
    triggered_team_total_cards_match Int32,
    opponent_total_cards_match Int32,
    card_count_match_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_per_card Nullable(Float32),
    opponent_fouls_per_card Nullable(Float32),
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_frustration_peak (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_cards_while_trailing_late Int32,
    trigger_threshold_minute Int32,
    triggered_team_cards_while_trailing_late Int32,
    opponent_cards_while_trailing_late Int32,
    cards_while_trailing_late_delta Int32,
    triggered_team_first_trailing_card_minute Int32,
    triggered_team_last_trailing_card_minute Int32,
    triggered_team_score_at_first_trailing_card Int32,
    opponent_score_at_first_trailing_card Int32,
    score_margin_at_first_trailing_card Int32,
    min_score_margin_during_trailing_cards Int32,
    triggered_team_yellow_cards_while_trailing_late Int32,
    opponent_yellow_cards_while_trailing_late Int32,
    triggered_team_red_cards_while_trailing_late Int32,
    opponent_red_cards_while_trailing_late Int32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_late_trailing_cards_share_pct Nullable(Float32),
    opponent_late_trailing_cards_share_pct Nullable(Float32),
    late_trailing_cards_share_delta_pct Nullable(Float32),
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_away_hostility (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_card_count_delta Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    card_count_above_threshold Int32,
    triggered_team_cards_share_pct Float32,
    opponent_cards_share_pct Float32,
    triggered_team_yellow_cards Int32,
    opponent_yellow_cards Int32,
    yellow_cards_delta Int32,
    triggered_team_red_cards Int32,
    opponent_red_cards Int32,
    red_cards_delta Int32,
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_fouls_share_pct Float32,
    opponent_fouls_share_pct Float32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_team_discipline_cards_hostile_territory (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_card_minus_shots_on_target Int32,
    triggered_team_total_cards Int32,
    opponent_total_cards Int32,
    card_count_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_cards_minus_shots_on_target Int32,
    opponent_cards_minus_shots_on_target Int32,
    cards_minus_shots_on_target_delta Int32,
    cards_minus_shots_on_target_above_threshold Int32,
    triggered_team_shots_on_target_rate_pct Nullable(Float32),
    opponent_shots_on_target_rate_pct Nullable(Float32),
    shots_on_target_rate_delta_pct Nullable(Float32),
    triggered_team_fouls_committed Int32,
    opponent_fouls_committed Int32,
    fouls_committed_delta Int32,
    triggered_team_duels_won Int32,
    opponent_duels_won Int32,
    triggered_team_tackles_won Int32,
    opponent_tackles_won Int32,
    triggered_team_interceptions Int32,
    opponent_interceptions Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
