-- Signal tables for entity=player, family=shooting, subfamily=goals

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_clinical_brace (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_max_expected_goals Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    goals_above_threshold Int32,
    expected_goals_below_threshold Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_clutch_brace_winning (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_equalizer_goals Int32,
    trigger_threshold_min_decisive_winning_goals Int32,
    triggered_player_equalizer_goals Int32,
    triggered_player_decisive_winning_goals Int32,
    triggered_player_first_equalizer_minute Int32,
    triggered_player_first_equalizer_added_time Int32,
    triggered_player_first_equalizer_effective_minute Int32,
    triggered_player_first_decisive_winning_goal_minute Int32,
    triggered_player_first_decisive_winning_goal_added_time Int32,
    triggered_player_first_decisive_winning_goal_effective_minute Int32,
    triggered_team_score_before_first_equalizer Int32,
    opponent_score_before_first_equalizer Int32,
    triggered_team_score_after_first_equalizer Int32,
    opponent_score_after_first_equalizer Int32,
    triggered_team_score_before_first_decisive_winning_goal Int32,
    opponent_score_before_first_decisive_winning_goal Int32,
    triggered_team_score_after_first_decisive_winning_goal Int32,
    opponent_score_after_first_decisive_winning_goal Int32,
    minutes_between_first_equalizer_and_first_decisive_winning_goal Int32,
    final_goal_margin Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_the_tap_in_merchant (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_min_expected_goals Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    goals_above_threshold Int32,
    expected_goals_above_threshold Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_man_of_the_match_output (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_expected_goals Float32,
    trigger_threshold_min_expected_assists Float32,
    trigger_threshold_min_expected_goal_involvement Float32,
    triggered_player_goals Int32,
    triggered_player_assists Int32,
    triggered_player_expected_goals Float32,
    triggered_player_expected_assists Float32,
    triggered_player_expected_goal_involvement Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_chances_created Int32,
    triggered_player_minutes_played Int32,
    expected_goals_above_threshold Float32,
    expected_assists_above_threshold Float32,
    expected_goal_involvement_above_threshold Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_assists_pct Float32,
    player_share_of_team_expected_assists_pct Float32,
    player_share_of_team_chances_created_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_rapid_brace (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_max_goal_window_minutes Int32,
    triggered_player_first_rapid_goal_minute Int32,
    triggered_player_first_rapid_goal_added_time Int32,
    triggered_player_first_rapid_goal_effective_minute Int32,
    triggered_player_second_rapid_goal_minute Int32,
    triggered_player_second_rapid_goal_added_time Int32,
    triggered_player_second_rapid_goal_effective_minute Int32,
    minutes_between_rapid_brace_goals Int32,
    triggered_player_rapid_brace_pair_count Int32,
    goals_above_threshold Int32,
    rapid_brace_window_margin_minutes Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_shot_conversion_peak (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_exact_goals Int32,
    trigger_threshold_exact_total_shots Int32,
    triggered_player_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_non_goal_shots Int32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_first_half_dominator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_first_half_goals Int32,
    trigger_threshold_goal_period LowCardinality(String),
    triggered_player_first_half_goals Int32,
    triggered_player_first_half_goal_share_of_match_goals_pct Float32,
    triggered_player_first_half_first_goal_minute Int32,
    triggered_player_first_half_first_goal_added_time Int32,
    triggered_player_first_half_first_goal_effective_minute Int32,
    triggered_player_first_half_last_goal_minute Int32,
    triggered_player_first_half_last_goal_added_time Int32,
    triggered_player_first_half_last_goal_effective_minute Int32,
    goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_first_half_non_own_goals Int32,
    opponent_first_half_non_own_goals Int32,
    first_half_non_own_goal_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_headers_only (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    triggered_player_goals Int32,
    triggered_player_header_goals Int32,
    triggered_player_non_header_goals Int32,
    triggered_player_header_goal_share_pct Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_header_shots Int32,
    triggered_player_header_shots_on_target Int32,
    triggered_player_header_shot_accuracy_pct Float32,
    triggered_player_expected_goals Float32,
    triggered_player_header_expected_goals Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    goals_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_header_goals Int32,
    opponent_header_goals Int32,
    triggered_team_header_shots Int32,
    opponent_header_shots Int32,
    triggered_team_header_expected_goals Float32,
    opponent_header_expected_goals Float32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_header_goals_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_defensive_scorer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_set_piece_goals Int32,
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_goals Int32,
    triggered_player_set_piece_goals Int32,
    triggered_player_corner_goals Int32,
    triggered_player_non_set_piece_goals Int32,
    triggered_player_set_piece_goal_share_pct Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_set_piece_shots Int32,
    triggered_player_set_piece_shots_on_target Int32,
    triggered_player_set_piece_shot_accuracy_pct Float32,
    triggered_player_expected_goals Float32,
    triggered_player_set_piece_expected_goals Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    set_piece_goals_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_set_piece_goals Int32,
    opponent_set_piece_goals Int32,
    triggered_team_set_piece_shots Int32,
    opponent_set_piece_shots Int32,
    triggered_team_set_piece_expected_goals Float32,
    opponent_set_piece_expected_goals Float32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_set_piece_goals_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_shot_volume_monster (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_total_shots Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    shots_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_box_dominator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_touches_opposition_box Int32,
    trigger_threshold_min_total_shots Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_total_touches Int32,
    triggered_player_minutes_played Int32,
    box_touches_above_threshold Int32,
    shots_above_threshold Int32,
    box_touches_per_shot Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_touches_opposition_box_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_volume_over_quality (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_total_shots Int32,
    trigger_threshold_max_expected_goals_per_shot Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_player_max_shot_expected_goals Float32,
    triggered_player_high_expected_goals_shots Int32,
    shots_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_shot_magnet (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_player_share_of_team_total_shots_pct Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    player_share_of_team_total_shots_pct Float32,
    player_shot_share_above_threshold_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_blocked_shot_frustration (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_blocked_shots Int32,
    triggered_player_blocked_shots Int32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_player_blocked_shot_ratio_pct Float32,
    blocked_shots_above_threshold Int32,
    triggered_player_unblocked_shots Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_blocked_shots Int32,
    opponent_blocked_shots Int32,
    blocked_shots_delta Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_blocked_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_high_xg_no_shot (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_touches_opposition_box Int32,
    trigger_threshold_max_total_shots Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_total_touches Int32,
    triggered_player_minutes_played Int32,
    box_touches_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_touches_opposition_box_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_first_minute_goal (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_first_minute_goals Int32,
    trigger_threshold_max_goal_minute Int32,
    trigger_threshold_max_goal_added_time Int32,
    triggered_player_first_minute_goals Int32,
    triggered_player_first_minute_goal_share_of_match_goals_pct Float32,
    triggered_player_first_minute_first_goal_minute Int32,
    triggered_player_first_minute_first_goal_added_time Int32,
    triggered_player_first_minute_first_goal_effective_minute Int32,
    triggered_player_first_minute_last_goal_minute Int32,
    triggered_player_first_minute_last_goal_added_time Int32,
    triggered_player_first_minute_last_goal_effective_minute Int32,
    goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_first_minute_non_own_goals Int32,
    opponent_first_minute_non_own_goals Int32,
    first_minute_non_own_goal_delta Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_wasteful_finisher (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_expected_goals Float32,
    trigger_threshold_max_goals Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    expected_goals_above_threshold Float32,
    expected_goals_wasted Float32,
    triggered_player_shots_without_goal Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_xg_accumulator_midfielder (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_expected_goals Float32,
    trigger_threshold_required_usual_playing_position_id Int32,
    trigger_threshold_excluded_position_id Int32,
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    expected_goals_above_threshold Float32,
    expected_goals_wasted Float32,
    triggered_player_shots_without_goal Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_midfield_sniper (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_outside_box_goals Int32,
    trigger_threshold_required_usual_playing_position_id Int32,
    trigger_threshold_excluded_position_id Int32,
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    triggered_player_outside_box_goals Int32,
    triggered_player_outside_box_shots Int32,
    triggered_player_outside_box_shots_on_target Int32,
    triggered_player_outside_box_expected_goals Float32,
    triggered_player_outside_box_shot_accuracy_pct Float32,
    triggered_player_outside_box_goal_conversion_pct Float32,
    triggered_player_goal_minus_outside_box_expected_goals Float32,
    triggered_player_total_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_total_expected_goals Float32,
    triggered_player_minutes_played Int32,
    outside_box_goals_above_threshold Int32,
    triggered_player_outside_box_goal_share_pct Float32,
    triggered_player_outside_box_shot_share_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_outside_box_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_impact_accumulator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_on_target Int32,
    trigger_threshold_max_goals Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    shots_on_target_above_threshold Int32,
    expected_goals_wasted Float32,
    triggered_player_shots_without_goal Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_high_volume_zero_test (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_total_shots Int32,
    trigger_threshold_max_shots_on_target Int32,
    trigger_threshold_max_blocked_shots Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shots_off_target Int32,
    triggered_player_blocked_shots Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shots_off_target_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    shots_above_threshold Int32,
    expected_goals_wasted Float32,
    triggered_player_shots_without_goal Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_off_target Int32,
    opponent_shots_off_target Int32,
    triggered_team_blocked_shots Int32,
    opponent_blocked_shots Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_off_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_big_chance_bottler (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_big_chances_missed Int32,
    triggered_player_big_chances_missed Int32,
    triggered_player_big_chances_missed_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_player_big_chances_missed_rate_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_big_chances_missed Int32,
    opponent_big_chances_missed Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_big_chances_missed_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_hat_trick_hero (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    goals_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_sniper_accuracy (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_total_shots Int32,
    trigger_threshold_min_shot_accuracy_pct Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shots_off_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    shots_above_threshold Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_long_range_specialist (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_outside_box_goals Int32,
    triggered_player_outside_box_goals Int32,
    triggered_player_outside_box_shots Int32,
    triggered_player_outside_box_shots_on_target Int32,
    triggered_player_outside_box_expected_goals Float32,
    triggered_player_outside_box_shot_accuracy_pct Float32,
    triggered_player_outside_box_goal_conversion_pct Float32,
    triggered_player_goal_minus_outside_box_expected_goals Float32,
    triggered_player_total_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_total_expected_goals Float32,
    triggered_player_minutes_played Int32,
    outside_box_goals_above_threshold Int32,
    triggered_player_outside_box_goal_share_pct Float32,
    triggered_player_outside_box_shot_share_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_outside_box_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_impossible_angle (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_shot_expected_goals Float32,
    triggered_player_low_expected_goals_goals Int32,
    triggered_player_low_expected_goals_shots Int32,
    triggered_player_low_expected_goals_shots_on_target Int32,
    triggered_player_low_expected_goals_sum_expected_goals Float32,
    triggered_player_low_expected_goals_min_goal_expected_goals Float32,
    triggered_player_low_expected_goals_avg_goal_expected_goals Float32,
    triggered_player_low_expected_goals_shot_accuracy_pct Float32,
    triggered_player_low_expected_goals_goal_conversion_pct Float32,
    triggered_player_goal_minus_low_expected_goals_sum_expected_goals Float32,
    triggered_player_total_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_total_expected_goals Float32,
    triggered_player_minutes_played Int32,
    low_expected_goals_goals_above_threshold Int32,
    triggered_player_low_expected_goals_goal_share_pct Float32,
    triggered_player_low_expected_goals_shot_share_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_distance_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_outside_box_shots Int32,
    triggered_player_outside_box_goals Int32,
    triggered_player_outside_box_shots Int32,
    triggered_player_outside_box_shots_on_target Int32,
    triggered_player_outside_box_expected_goals Float32,
    triggered_player_outside_box_shot_accuracy_pct Float32,
    triggered_player_outside_box_goal_conversion_pct Float32,
    triggered_player_goal_minus_outside_box_expected_goals Float32,
    triggered_player_total_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_total_expected_goals Float32,
    triggered_player_minutes_played Int32,
    outside_box_shots_above_threshold Int32,
    triggered_player_outside_box_goal_share_pct Float32,
    triggered_player_outside_box_shot_share_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_shots_outside_box Int32,
    opponent_shots_outside_box Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_outside_box_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_freekick_master (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_direct_free_kick_goals Int32,
    triggered_player_direct_free_kick_goals Int32,
    triggered_player_direct_free_kick_shots Int32,
    triggered_player_direct_free_kick_shots_on_target Int32,
    triggered_player_direct_free_kick_expected_goals Float32,
    triggered_player_direct_free_kick_shot_accuracy_pct Float32,
    triggered_player_direct_free_kick_goal_conversion_pct Float32,
    triggered_player_goal_minus_direct_free_kick_expected_goals Float32,
    triggered_player_total_goals Int32,
    triggered_player_total_shots Int32,
    triggered_player_total_expected_goals Float32,
    triggered_player_minutes_played Int32,
    direct_free_kick_goals_above_threshold Int32,
    triggered_player_direct_free_kick_goal_share_pct Float32,
    triggered_player_direct_free_kick_shot_share_pct Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_direct_free_kick_goals Int32,
    opponent_direct_free_kick_goals Int32,
    triggered_team_direct_free_kick_shots Int32,
    opponent_direct_free_kick_shots Int32,
    triggered_team_direct_free_kick_expected_goals Float32,
    opponent_direct_free_kick_expected_goals Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_direct_free_kick_goals_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_clutch_equalizer (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goal_minute Int32,
    triggered_player_late_equalizer_goals Int32,
    triggered_player_first_late_equalizer_minute Int32,
    triggered_player_first_late_equalizer_added_time Int32,
    triggered_player_first_late_equalizer_effective_minute Int32,
    triggered_player_last_late_equalizer_minute Int32,
    triggered_player_last_late_equalizer_effective_minute Int32,
    triggered_team_score_before_first_late_equalizer Int32,
    opponent_score_before_first_late_equalizer Int32,
    triggered_team_score_after_first_late_equalizer Int32,
    opponent_score_after_first_late_equalizer Int32,
    late_equalizer_goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_late_winner_clutch (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goal_effective_minute Int32,
    triggered_player_late_winning_goals Int32,
    triggered_player_first_late_winning_goal_minute Int32,
    triggered_player_first_late_winning_goal_added_time Int32,
    triggered_player_first_late_winning_goal_effective_minute Int32,
    triggered_team_score_before_first_late_winning_goal Int32,
    opponent_score_before_first_late_winning_goal Int32,
    triggered_team_score_after_first_late_winning_goal Int32,
    opponent_score_after_first_late_winning_goal Int32,
    final_goal_margin Int32,
    late_winning_goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_super_sub_goal (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_max_minutes_from_substitution Int32,
    triggered_player_substitution_time Int32,
    triggered_player_first_super_sub_goal_minute Int32,
    triggered_player_first_super_sub_goal_added_time Int32,
    triggered_player_first_super_sub_goal_effective_minute Int32,
    minutes_from_substitution_to_first_super_sub_goal Int32,
    triggered_player_super_sub_goals Int32,
    super_sub_goals_above_threshold Int32,
    triggered_team_score_before_first_super_sub_goal Int32,
    opponent_score_before_first_super_sub_goal Int32,
    triggered_team_score_after_first_super_sub_goal Int32,
    opponent_score_after_first_super_sub_goal Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_high_velocity_finisher (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goals Int32,
    trigger_threshold_exclusive_max_minutes_played Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    goals_above_threshold Int32,
    minutes_below_threshold Int32,
    triggered_player_goals_per_90 Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_one_man_army (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_team_goals Int32,
    trigger_threshold_opponent_goals Int32,
    trigger_threshold_player_goals Int32,
    triggered_player_only_team_goals Int32,
    triggered_player_first_goal_minute Int32,
    triggered_player_first_goal_added_time Int32,
    triggered_player_first_goal_effective_minute Int32,
    triggered_team_score_before_only_goal Int32,
    opponent_score_before_only_goal Int32,
    triggered_team_score_after_only_goal Int32,
    opponent_score_after_only_goal Int32,
    triggered_player_goal_contribution_pct Float32,
    triggered_player_goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_persistent_threat (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_shots_per_segment Int32,
    trigger_threshold_segment_window_minutes Int32,
    trigger_threshold_required_segment_count Int32,
    triggered_player_shots_segment_00_15 Int32,
    triggered_player_shots_segment_16_30 Int32,
    triggered_player_shots_segment_31_45_plus Int32,
    triggered_player_shots_segment_46_60 Int32,
    triggered_player_shots_segment_61_75 Int32,
    triggered_player_shots_segment_76_90_plus Int32,
    triggered_player_shot_segments_hit_count Int32,
    triggered_player_shot_segment_coverage_pct Float32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_shot_conversion_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    player_share_of_team_shots_on_target_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_shooting_goals_winning_impact (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_goal_margin Int32,
    trigger_threshold_min_decisive_winning_goals Int32,
    triggered_player_decisive_winning_goals Int32,
    triggered_player_first_decisive_goal_minute Int32,
    triggered_player_first_decisive_goal_added_time Int32,
    triggered_player_first_decisive_goal_effective_minute Int32,
    triggered_team_score_before_first_decisive_goal Int32,
    opponent_score_before_first_decisive_goal Int32,
    triggered_team_score_after_first_decisive_goal Int32,
    opponent_score_after_first_decisive_goal Int32,
    final_goal_margin Int32,
    decisive_winning_goals_above_threshold Int32,
    triggered_player_goals Int32,
    triggered_player_expected_goals Float32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_expected_goals_per_shot Float32,
    triggered_player_goal_minus_expected_goals Float32,
    triggered_player_minutes_played Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_pct Float32,
    player_share_of_team_expected_goals_pct Float32,
    player_share_of_team_total_shots_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);
