-- Signal tables for entity=player, family=creativity, subfamily=playmaking

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_maestro_output (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_key_passes Int32,
    triggered_player_key_passes Int32,
    triggered_player_key_passes_above_threshold Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_box_penetrator (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_penalty_area_passes Int32,
    triggered_player_penalty_area_passes_proxy Int32,
    triggered_player_penalty_area_passes_proxy_source LowCardinality(String),
    triggered_player_penalty_area_passes_proxy_above_threshold Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_penalty_area_passes_proxy_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_cross_perfection (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_accurate_crosses Int32,
    trigger_threshold_min_cross_accuracy_pct Float32,
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_accuracy_pct Float32,
    triggered_player_accurate_crosses_above_threshold Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_accurate_crosses_pct Float32,
    player_share_of_team_cross_attempts_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_chance_machine (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_big_chances_created Int32,
    triggered_player_big_chances_created Int32,
    triggered_player_big_chances_created_above_threshold Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_big_chances_pct Float32,
    player_share_of_team_chances_created_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_line_breaker (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_directional_proxy Int32,
    triggered_player_passes_final_third_directional_proxy Int32,
    triggered_team_long_ball_attempts_directional_proxy Int32,
    triggered_player_directional_proxy_source LowCardinality(String),
    triggered_player_directional_proxy_value Int32,
    triggered_player_directional_proxy_above_threshold Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_half_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_box_to_box_playmaker (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    trigger_threshold_min_directional_proxy Int32,
    trigger_threshold_min_recoveries Int32,
    triggered_player_passes_final_third_directional_proxy Int32,
    triggered_team_long_ball_attempts_directional_proxy Int32,
    triggered_player_directional_proxy_source LowCardinality(String),
    triggered_player_directional_proxy_value Int32,
    triggered_player_directional_proxy_above_threshold Int32,
    triggered_player_recoveries Int32,
    triggered_player_recoveries_above_threshold Int32,
    triggered_team_recoveries Int32,
    opponent_recoveries Int32,
    recoveries_delta Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_recoveries_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_half_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_final_third_monopoly (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_successful_final_third_passes Int32,
    triggered_player_successful_final_third_passes Int32,
    triggered_player_successful_final_third_passes_above_threshold Int32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_half_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_fullback_playmaker (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    trigger_threshold_min_successful_box_passes_proxy Int32,
    trigger_threshold_required_usual_playing_position_id Int32,
    trigger_fullback_position_ids String,
    triggered_player_successful_box_passes_proxy Int32,
    triggered_player_successful_box_passes_proxy_source LowCardinality(String),
    triggered_player_successful_box_passes_proxy_above_threshold Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    player_share_of_team_box_passes_proxy_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_assist_brace (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_assists Int32,
    triggered_player_assists Int32,
    triggered_player_assists_above_threshold Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_chances_created Int32,
    triggered_player_assists_per_chance_created_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_assisted_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_deadball_wizard (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_corner_assists Int32,
    triggered_player_corner_assists Int32,
    triggered_player_corner_assists_above_threshold Int32,
    triggered_player_corner_chances_created Int32,
    triggered_player_corner_assisted_shots_on_target Int32,
    triggered_player_corner_assisted_shot_expected_goals Float32,
    triggered_player_assists Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_chances_created Int32,
    triggered_player_assists_per_chance_created_pct Float32,
    triggered_player_cross_attempts Int32,
    triggered_player_accurate_crosses Int32,
    triggered_player_cross_success_rate_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_corner_goals Int32,
    opponent_corner_goals Int32,
    triggered_team_corner_shots Int32,
    opponent_corner_shots Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_corner_goals_assisted_pct Float32,
    player_share_of_team_goals_assisted_pct Float32,
    player_share_of_team_crosses_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_assist_hat_trick (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_assists Int32,
    triggered_player_assists Int32,
    triggered_player_assists_above_threshold Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_chances_created Int32,
    triggered_player_assists_per_chance_created_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_goals_assisted_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_clutch_vision (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_goal_effective_minute Int32,
    triggered_player_late_winning_goal_assists Int32,
    triggered_player_first_late_winning_goal_assist_minute Int32,
    triggered_player_first_late_winning_goal_assist_added_time Int32,
    triggered_player_first_late_winning_goal_assist_effective_minute Int32,
    triggered_team_score_before_first_late_winning_goal_assist Int32,
    opponent_score_before_first_late_winning_goal_assist Int32,
    triggered_team_score_after_first_late_winning_goal_assist Int32,
    opponent_score_after_first_late_winning_goal_assist Int32,
    final_goal_margin Int32,
    late_winning_goal_assists_above_threshold Int32,
    triggered_player_assists Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_assists_pct Float32,
    player_share_of_team_chances_created_pct Float32,
    player_share_of_team_passes_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_unselfish_forward (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    trigger_threshold_min_key_passes Int32,
    trigger_threshold_max_total_shots Int32,
    trigger_threshold_required_usual_playing_position_id Int32,
    triggered_player_key_passes Int32,
    triggered_player_key_passes_above_threshold Int32,
    triggered_player_total_shots Int32,
    triggered_player_shots_on_target Int32,
    triggered_player_shot_accuracy_pct Float32,
    triggered_player_assists Int32,
    triggered_player_expected_assists Float32,
    triggered_player_chances_created Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_total_key_passes Int32,
    opponent_total_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shot_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_key_passes_pct Float32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_expected_wizard (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_expected_assists Float32,
    trigger_threshold_max_assists Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assists Int32,
    triggered_player_assist_minus_expected_assists Float32,
    expected_assists_above_threshold Float32,
    triggered_player_chances_created Int32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_isolated_creativity (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_player_share_of_team_key_passes_pct Float32,
    triggered_player_key_passes Int32,
    triggered_team_total_key_passes Int32,
    player_share_of_team_key_passes_pct Float32,
    player_share_of_team_key_passes_above_threshold_pct Float32,
    triggered_player_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_the_quarterback (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_player_role_group LowCardinality(String),
    triggered_player_position_id Int32,
    triggered_player_usual_playing_position_id Int32,
    trigger_threshold_min_accurate_long_balls Int32,
    triggered_player_accurate_long_balls Int32,
    triggered_player_accurate_long_balls_above_threshold Int32,
    triggered_player_long_ball_attempts Int32,
    triggered_player_long_ball_success_rate_pct Float32,
    triggered_player_total_passes Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_chances_created Int32,
    triggered_player_expected_assists Float32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_accurate_long_balls Int32,
    opponent_accurate_long_balls Int32,
    triggered_team_long_ball_accuracy_pct Float32,
    opponent_long_ball_accuracy_pct Float32,
    long_ball_accuracy_delta_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    player_share_of_team_accurate_long_balls_pct Float32,
    player_share_of_team_long_ball_attempts_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_player_creativity_playmaking_high_value_turnover (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_player_id Int32,
    triggered_player_name Nullable(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_key_passes Int32,
    trigger_threshold_max_assists Int32,
    triggered_player_key_passes Int32,
    triggered_player_key_passes_above_threshold Int32,
    triggered_player_assists Int32,
    triggered_player_unconverted_key_passes Int32,
    triggered_player_expected_assists Float32,
    triggered_player_assist_minus_expected_assists Float32,
    triggered_player_passes_final_third Int32,
    triggered_player_touches_opposition_box Int32,
    triggered_player_accurate_passes Int32,
    triggered_player_total_passes Int32,
    triggered_player_pass_accuracy_pct Float32,
    triggered_player_minutes_played Int32,
    triggered_player_touches Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_accurate_passes Int32,
    opponent_accurate_passes Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    player_share_of_team_passes_pct Float32,
    player_share_of_team_opposition_box_touches_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side, triggered_player_id)
PARTITION BY toYYYYMM(match_date);
