-- Signal tables for entity=match, family=possession, subfamily=passing

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_momentum_swing (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    possession_momentum_swing_pp Float32,
    triggered_team_possession_first_half_pct Float32,
    triggered_team_possession_second_half_pct Float32,
    opponent_possession_first_half_pct Float32,
    opponent_possession_second_half_pct Float32,
    possession_swing_delta Float32,
    triggered_team_pass_attempts_first_half Int32,
    triggered_team_pass_attempts_second_half Int32,
    opponent_pass_attempts_first_half Int32,
    opponent_pass_attempts_second_half Int32,
    triggered_team_pass_accuracy_first_half_pct Nullable(Float32),
    triggered_team_pass_accuracy_second_half_pct Nullable(Float32),
    opponent_pass_accuracy_first_half_pct Nullable(Float32),
    opponent_pass_accuracy_second_half_pct Nullable(Float32),
    triggered_team_pass_accuracy_delta_pct Nullable(Float32),
    opponent_pass_accuracy_delta_pct Nullable(Float32),
    triggered_team_opposition_half_passes_first_half Int32,
    triggered_team_opposition_half_passes_second_half Int32,
    opponent_opposition_half_passes_first_half Int32,
    opponent_opposition_half_passes_second_half Int32,
    triggered_team_xg_first_half Float32,
    triggered_team_xg_second_half Float32,
    opponent_xg_first_half Float32,
    opponent_xg_second_half Float32,
    xg_swing_delta Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_dribble_fest (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_successful_dribbles Int32,
    match_total_successful_dribbles Int32,
    match_total_dribble_attempts Int32,
    match_dribble_success_pct Float32,
    triggered_team_successful_dribbles Int32,
    opponent_successful_dribbles Int32,
    triggered_team_dribble_attempts Int32,
    opponent_dribble_attempts Int32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_successful_dribble_share_pct Float32,
    opponent_successful_dribble_share_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_dead_zone_game (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_opposition_six_yard_box_touches Int32,
    match_total_opposition_box_touches_proxy Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    match_total_pass_attempts Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    match_total_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_passing_clinic (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_pct Float32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_gap_pct Float32,
    match_min_half_pass_accuracy_pct Float32,
    triggered_team_pass_accuracy_first_half_pct Float32,
    triggered_team_pass_accuracy_second_half_pct Float32,
    opponent_pass_accuracy_first_half_pct Float32,
    opponent_pass_accuracy_second_half_pct Float32,
    triggered_team_pass_accuracy_floor_pct Float32,
    opponent_pass_accuracy_floor_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_attempts_first_half Int32,
    triggered_team_pass_attempts_second_half Int32,
    opponent_pass_attempts_first_half Int32,
    opponent_pass_attempts_second_half Int32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_clinical_match (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_match_total_goals Int32,
    trigger_threshold_match_total_xg Float32,
    match_total_goals Int32,
    match_total_xg Float32,
    match_goal_minus_xg Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_gap Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    triggered_team_goals_minus_xg Float32,
    opponent_goals_minus_xg Float32,
    goals_minus_xg_gap Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_heavy_rotation (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_match_total_player_touches Int32,
    trigger_threshold_max_player_touches Int32,
    match_total_player_touches Int32,
    match_max_player_touches Int32,
    match_players_recorded Int32,
    match_average_player_touches Float32,
    triggered_team_total_player_touches Int32,
    opponent_total_player_touches Int32,
    triggered_team_max_player_touches Int32,
    opponent_max_player_touches Int32,
    triggered_team_players_recorded Int32,
    opponent_players_recorded Int32,
    triggered_team_top_touch_player_id Nullable(Int32),
    triggered_team_top_touch_player_name Nullable(String),
    triggered_team_top_touch_player_touches Int32,
    opponent_top_touch_player_id Nullable(Int32),
    opponent_top_touch_player_name Nullable(String),
    opponent_top_touch_player_touches Int32,
    triggered_team_touch_share_pct Float32,
    opponent_touch_share_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_possession_stalemate (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_gap_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_final_third_passes Int32,
    opponent_final_third_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_unproductive_game (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    match_total_pass_attempts Int32,
    match_total_shots Int32,
    match_passes_per_shot Nullable(Float32),
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_pass_share_pct Nullable(Float32),
    triggered_team_shot_share_pct Nullable(Float32),
    triggered_team_pass_accuracy_pct Nullable(Float32),
    opponent_pass_accuracy_pct Nullable(Float32),
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    match_total_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_clean_game (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_turnovers Int32,
    match_total_turnovers Int32,
    match_total_pass_attempts Int32,
    match_turnovers_per_100_pass_attempts Float32,
    triggered_team_turnovers Int32,
    opponent_turnovers Int32,
    triggered_team_turnover_share_pct Float32,
    triggered_team_failed_passes Int32,
    opponent_failed_passes Int32,
    triggered_team_failed_dribbles Int32,
    opponent_failed_dribbles Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_high_turnover_affair (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_turnovers Int32,
    match_total_turnovers Int32,
    match_total_pass_attempts Int32,
    match_turnovers_per_100_pass_attempts Float32,
    triggered_team_turnovers Int32,
    opponent_turnovers Int32,
    triggered_team_turnover_share_pct Float32,
    triggered_team_failed_passes Int32,
    opponent_failed_passes Int32,
    triggered_team_failed_dribbles Int32,
    opponent_failed_dribbles Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_dribble_success_pct Float32,
    opponent_dribble_success_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_early_tactical_lock (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_window_minutes Int32,
    match_first_30_total_shots_on_target Int32,
    triggered_team_first_30_shots_on_target Int32,
    opponent_first_30_shots_on_target Int32,
    match_first_30_total_shots Int32,
    triggered_team_first_30_total_shots Int32,
    opponent_first_30_total_shots Int32,
    match_first_30_first_shot_minute Nullable(Int32),
    triggered_team_first_30_first_shot_minute Nullable(Int32),
    opponent_first_30_first_shot_minute Nullable(Int32),
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_set_piece_dominance (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    match_total_pass_attempts Int32,
    match_total_dead_ball_restart_passes_proxy Int32,
    match_dead_ball_restart_pass_share_pct Float32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_dead_ball_restart_passes_proxy Int32,
    opponent_dead_ball_restart_passes_proxy Int32,
    triggered_team_dead_ball_restart_pass_share_pct Float32,
    opponent_dead_ball_restart_pass_share_pct Float32,
    triggered_team_dead_ball_share_of_match_passes_pct Float32,
    opponent_dead_ball_share_of_match_passes_pct Float32,
    triggered_team_dead_ball_share_of_match_dead_ball_restart_passes_pct Float32,
    opponent_dead_ball_share_of_match_dead_ball_restart_passes_pct Float32,
    triggered_team_player_throws Int32,
    opponent_player_throws Int32,
    triggered_team_corners Int32,
    opponent_corners Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_set_piece_shots Int32,
    opponent_set_piece_shots Int32,
    triggered_team_set_play_xg Float32,
    opponent_set_play_xg Float32,
    set_play_xg_delta Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_wing_play_extravaganza (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    match_total_cross_attempts Int32,
    match_total_accurate_crosses Int32,
    match_cross_accuracy_pct Float32,
    triggered_team_cross_attempts Int32,
    opponent_cross_attempts Int32,
    triggered_team_accurate_crosses Int32,
    opponent_accurate_crosses Int32,
    triggered_team_cross_share_pct Float32,
    opponent_cross_share_pct Float32,
    triggered_team_cross_accuracy_pct Float32,
    opponent_cross_accuracy_pct Float32,
    triggered_team_crosses_per_shot Nullable(Float32),
    opponent_crosses_per_shot Nullable(Float32),
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_gap Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_keeper_playmaking_battle (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    triggered_goalkeeper_player_id Int32,
    triggered_goalkeeper_player_name Nullable(String),
    opponent_goalkeeper_player_id Int32,
    opponent_goalkeeper_player_name Nullable(String),
    triggered_goalkeeper_pass_attempts Int32,
    opponent_goalkeeper_pass_attempts Int32,
    triggered_goalkeeper_accurate_passes Int32,
    opponent_goalkeeper_accurate_passes Int32,
    triggered_goalkeeper_pass_accuracy_pct Float32,
    opponent_goalkeeper_pass_accuracy_pct Float32,
    triggered_goalkeeper_share_of_team_passes_pct Float32,
    opponent_goalkeeper_share_of_team_passes_pct Float32,
    match_total_goalkeeper_pass_attempts Int32,
    match_total_goalkeeper_accurate_passes Int32,
    match_goalkeeper_pass_accuracy_pct Float32,
    goalkeeper_pass_attempt_delta Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_own_half_passes Int32,
    opponent_own_half_passes Int32,
    triggered_team_long_ball_attempts Int32,
    opponent_long_ball_attempts Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);

CREATE TABLE IF NOT EXISTS gold_signals.sig_match_possession_passing_counter_vs_bus (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    possession_dominant_side LowCardinality(String),
    possession_dominant_team_id Nullable(Int32),
    possession_dominant_team_name Nullable(String),
    counter_attacking_side LowCardinality(String),
    counter_attacking_team_id Nullable(Int32),
    counter_attacking_team_name Nullable(String),
    possession_dominant_team_possession_pct Float32,
    counter_attacking_team_counter_attacks_proxy Int32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    triggered_team_counter_attacks_proxy Int32,
    opponent_counter_attacks_proxy Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    triggered_team_clearances Int32,
    opponent_clearances Int32,
    triggered_team_xg Float32,
    opponent_xg Float32,
    xg_delta Float32,
    possession_gap_pct Float32,
    counter_attack_gap_proxy Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
