ATTACH TABLE _ UUID '8c428833-90bb-4257-87c5-1de4f2dea27f'
(
    `match_id` Int32,
    `player_id` Nullable(Int32),
    `player_name` Nullable(String),
    `opta_id` Nullable(String),
    `team_id` Nullable(Int32),
    `team_name` Nullable(String),
    `is_goalkeeper` Nullable(UInt8),
    `fotmob_rating` Nullable(Float32),
    `minutes_played` Nullable(Int32),
    `goals` Nullable(Int32),
    `assists` Nullable(Int32),
    `total_shots` Nullable(Int32),
    `shots_on_target` Nullable(Int32),
    `shots_off_target` Nullable(Int32),
    `blocked_shots` Nullable(Int32),
    `expected_goals` Nullable(Float32),
    `expected_assists` Nullable(Float32),
    `xg_plus_xa` Nullable(Float32),
    `xg_non_penalty` Nullable(Float32),
    `chances_created` Nullable(Int32),
    `touches` Nullable(Int32),
    `touches_opp_box` Nullable(Int32),
    `successful_dribbles` Nullable(Int32),
    `dribble_attempts` Nullable(Int32),
    `dribble_success_rate` Nullable(Float32),
    `accurate_passes` Nullable(Int32),
    `total_passes` Nullable(Int32),
    `pass_accuracy` Nullable(Float32),
    `passes_final_third` Nullable(Int32),
    `accurate_crosses` Nullable(Int32),
    `cross_attempts` Nullable(Int32),
    `cross_success_rate` Nullable(Float32),
    `accurate_long_balls` Nullable(Int32),
    `long_ball_attempts` Nullable(Int32),
    `long_ball_success_rate` Nullable(Float32),
    `tackles_won` Nullable(Int32),
    `tackle_attempts` Nullable(Int32),
    `tackle_success_rate` Nullable(Float32),
    `interceptions` Nullable(Int32),
    `clearances` Nullable(Int32),
    `defensive_actions` Nullable(Int32),
    `recoveries` Nullable(Int32),
    `dribbled_past` Nullable(Int32),
    `duels_won` Nullable(Int32),
    `duels_lost` Nullable(Int32),
    `ground_duels_won` Nullable(Int32),
    `ground_duel_attempts` Nullable(Int32),
    `ground_duel_success_rate` Nullable(Float32),
    `aerial_duels_won` Nullable(Int32),
    `aerial_duel_attempts` Nullable(Int32),
    `aerial_duel_success_rate` Nullable(Float32),
    `fouls_committed` Nullable(Int32),
    `was_fouled` Nullable(Int32),
    `shotmap_count` Nullable(Int32),
    `average_xg_per_shot` Nullable(Float32),
    `total_xg` Nullable(Float32),
    `fun_facts` Array(Nullable(String)),
    `inserted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, assumeNotNull(player_id))
SETTINGS index_granularity = 8192
