INSERT INTO silver.match_period_stat
SELECT
    p.match_id,
    ifNull(toDateOrNull(g.match_time_utc_date), toDate('1970-01-01')) AS match_date,
    p.period,
    p.ball_possession_home, p.ball_possession_away,
    p.expected_goals_home, p.expected_goals_away,
    p.expected_goals_open_play_home, p.expected_goals_open_play_away,
    p.expected_goals_set_play_home, p.expected_goals_set_play_away,
    p.expected_goals_non_penalty_home, p.expected_goals_non_penalty_away,
    p.expected_goals_on_target_home, p.expected_goals_on_target_away,
    p.distance_covered_home, p.distance_covered_away,
    p.walking_distance_home, p.walking_distance_away,
    p.running_distance_home, p.running_distance_away,
    p.sprinting_distance_home, p.sprinting_distance_away,
    p.number_of_sprints_home, p.number_of_sprints_away,
    p.top_speed_home, p.top_speed_away,
    p.total_shots_home, p.total_shots_away,
    p.shots_on_target_home, p.shots_on_target_away,
    p.shots_off_target_home, p.shots_off_target_away,
    p.blocked_shots_home, p.blocked_shots_away,
    p.shots_woodwork_home, p.shots_woodwork_away,
    p.shots_inside_box_home, p.shots_inside_box_away,
    p.shots_outside_box_home, p.shots_outside_box_away,
    p.big_chances_home, p.big_chances_away,
    p.big_chances_missed_home, p.big_chances_missed_away,
    p.passes_home, p.passes_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_passes_home, ''))[1], '')) AS accurate_passes_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_passes_home, ''))[2], '')) AS pass_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_passes_away, ''))[1], '')) AS accurate_passes_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_passes_away, ''))[2], '')) AS pass_attempts_away,
    p.own_half_passes_home, p.own_half_passes_away,
    p.opposition_half_passes_home, p.opposition_half_passes_away,
    p.player_throws_home, p.player_throws_away,
    p.touches_opp_box_home, p.touches_opp_box_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.long_balls_accurate_home, ''))[1], '')) AS accurate_long_balls_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.long_balls_accurate_home, ''))[2], '')) AS long_ball_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.long_balls_accurate_away, ''))[1], '')) AS accurate_long_balls_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.long_balls_accurate_away, ''))[2], '')) AS long_ball_attempts_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_crosses_home, ''))[1], '')) AS accurate_crosses_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_crosses_home, ''))[2], '')) AS cross_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_crosses_away, ''))[1], '')) AS accurate_crosses_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.accurate_crosses_away, ''))[2], '')) AS cross_attempts_away,
    p.interceptions_home, p.interceptions_away,
    p.clearances_home, p.clearances_away,
    p.shot_blocks_home, p.shot_blocks_away,
    p.keeper_saves_home, p.keeper_saves_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.tackles_succeeded_home, ''))[1], '')) AS tackles_succeeded_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.tackles_succeeded_home, ''))[2], '')) AS tackle_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.tackles_succeeded_away, ''))[1], '')) AS tackles_succeeded_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.tackles_succeeded_away, ''))[2], '')) AS tackle_attempts_away,
    p.duels_won_home, p.duels_won_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.ground_duels_won_home, ''))[1], '')) AS ground_duels_won_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.ground_duels_won_home, ''))[2], '')) AS ground_duel_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.ground_duels_won_away, ''))[1], '')) AS ground_duels_won_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.ground_duels_won_away, ''))[2], '')) AS ground_duel_attempts_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.aerials_won_home, ''))[1], '')) AS aerials_won_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.aerials_won_home, ''))[2], '')) AS aerial_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.aerials_won_away, ''))[1], '')) AS aerials_won_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.aerials_won_away, ''))[2], '')) AS aerial_attempts_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.dribbles_succeeded_home, ''))[1], '')) AS dribbles_succeeded_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.dribbles_succeeded_home, ''))[2], '')) AS dribble_attempts_home,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.dribbles_succeeded_away, ''))[1], '')) AS dribbles_succeeded_away,
    toInt32OrNull(nullIf(splitByChar('/', ifNull(p.dribbles_succeeded_away, ''))[2], '')) AS dribble_attempts_away,
    p.yellow_cards_home, p.yellow_cards_away,
    p.red_cards_home, p.red_cards_away,
    p.fouls_home, p.fouls_away,
    p.corners_home, p.corners_away,
    p.offsides_home, p.offsides_away,
    now() AS _loaded_at
FROM bronze.period AS p FINAL
LEFT JOIN bronze.general AS g FINAL ON p.match_id = g.match_id;
