-- silver.match
CREATE TABLE IF NOT EXISTS silver.match
(
    match_id                        Int32,
    match_date                      Date,
    match_time_utc                  Nullable(DateTime),
    match_started                   UInt8,
    match_finished                  UInt8,
    match_round                     Nullable(String),
    coverage_level                  LowCardinality(Nullable(String)),
    league_id                       Nullable(Int32),
    league_name                     LowCardinality(Nullable(String)),
    league_round_name               Nullable(String),
    parent_league_id                Nullable(Int32),
    parent_league_name              Nullable(String),
    parent_league_season            Nullable(String),
    parent_league_tournament_id     Nullable(Int32),
    country_code                    LowCardinality(Nullable(String)),
    tournament_id                   Nullable(Int32),
    tournament_name                 Nullable(String),
    tournament_round                Nullable(String),
    tournament_link                 Nullable(String),
    home_team_id                    Nullable(Int32),
    home_team_name                  Nullable(String),
    away_team_id                    Nullable(Int32),
    away_team_name                  Nullable(String),
    home_score                      Nullable(Int32),
    away_score                      Nullable(Int32),
    full_score                      Nullable(String),
    game_started                    UInt8 DEFAULT 0,
    game_finished                   UInt8 DEFAULT 0,
    game_cancelled                  UInt8 DEFAULT 0,
    first_half_started              Nullable(DateTime),
    first_half_ended                Nullable(DateTime),
    second_half_started             Nullable(DateTime),
    second_half_ended               Nullable(DateTime),
    first_extra_half_started        Nullable(DateTime),
    second_extra_half_started       Nullable(DateTime),
    game_ended                      Nullable(DateTime),
    stadium_name                    Nullable(String),
    stadium_city                    Nullable(String),
    stadium_country                 LowCardinality(Nullable(String)),
    stadium_latitude                Nullable(Float64),
    stadium_longitude               Nullable(Float64),
    stadium_capacity                Nullable(Int32),
    stadium_surface                 LowCardinality(Nullable(String)),
    attendance                      Nullable(Int32),
    match_date_verified             Nullable(UInt8),
    referee_name                    Nullable(String),
    referee_country                 LowCardinality(Nullable(String)),
    _loaded_at                      DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_loaded_at)
PARTITION BY toYYYYMM(match_date)
ORDER BY match_id;
